import { describe, expect, it } from 'vitest';
import { OracleStrategy } from '../../strategies/OracleStrategy.js';
import type { NormalizedField } from '@ddlbuilder/shared-types';

describe('OracleStrategy', () => {
  const strategy = new OracleStrategy();

  it('应返回 oracle 数据库类型', () => {
    expect(strategy.getDatabaseType()).toBe('oracle');
  });

  it('应生成 Oracle 风格的默认值与注释 DDL', () => {
    const fields: NormalizedField[] = [
      {
        name: 'id',
        type: 'int',
        comment: '主键',
        nullable: false,
        defaultKind: 'auto_increment',
        defaultValue: '',
        onUpdate: 'none',
      },
      {
        name: 'created_date',
        type: 'date',
        comment: '创建日期',
        nullable: false,
        defaultKind: 'current_timestamp',
        defaultValue: '',
        onUpdate: 'none',
      },
      {
        name: 'created_at',
        type: 'timestamp',
        comment: '创建时间',
        nullable: false,
        defaultKind: 'current_timestamp',
        defaultValue: '',
        onUpdate: 'none',
      },
      {
        name: 'trace_id',
        type: 'uuid',
        comment: "追踪'ID",
        nullable: false,
        defaultKind: 'uuid',
        defaultValue: '',
        onUpdate: 'none',
      },
    ];

    const ddl = strategy.generateTableDDL('schema1.users', "用户'表", fields);

    expect(ddl).toContain('CREATE TABLE schema1.users');
    expect(ddl).toContain('id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL');
    expect(ddl).toContain('created_date DATE DEFAULT SYSDATE NOT NULL');
    expect(ddl).toContain('created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL');
    expect(ddl).toContain('trace_id CHAR(36) DEFAULT SYS_GUID() NOT NULL');
    expect(ddl).toContain("COMMENT ON TABLE schema1.users IS '用户''表'");
    expect(ddl).toContain("COMMENT ON COLUMN schema1.users.trace_id IS '追踪''ID'");
  });
});
