import { describe, expect, it } from 'vitest';
import { ProfiledDDLStrategy } from '../../strategies/ProfiledDDLStrategy.js';
import type { NormalizedField } from '@ddlbuilder/shared-types';

describe('PostgresStrategy', () => {
  it('quotes table, column, index, and referenced key names consistently', () => {
    const strategy = new ProfiledDDLStrategy('postgresql');
    const index = {
      id: 'index',
      name: 'OrderKey',
      kind: 'unique_index',
      fields: [{ name: 'order', direction: 'ASC' as const }],
    };
    expect(strategy.generateIndexDDL('Audit.Users', index)).toBe(
      'CREATE UNIQUE INDEX "OrderKey" ON "Audit"."Users" ("order" ASC);',
    );
    expect(
      strategy.generateForeignKeyDDL('Audit.Users', {
        id: 'fk',
        name: 'OwnerFk',
        fields: ['OwnerId'],
        refSchema: 'Auth',
        refTable: 'Users',
        refFields: ['Id'],
      }),
    ).toBe(
      'ALTER TABLE "Audit"."Users" ADD CONSTRAINT "OwnerFk" FOREIGN KEY ("OwnerId") REFERENCES "Auth"."Users" ("Id");',
    );
    expect(
      strategy.generateTableDDL('Audit.Users', 'users', [
        {
          name: 'order',
          type: 'int',
          nullable: true,
          comment: 'order',
          defaultKind: 'none',
          defaultValue: '',
          onUpdate: 'none',
        },
      ]),
    ).toBe(
      'CREATE TABLE "Audit"."Users" (\n  "order" INTEGER\n);\nCOMMENT ON TABLE "Audit"."Users" IS \'users\';\nCOMMENT ON COLUMN "Audit"."Users"."order" IS \'order\';',
    );
  });

  it('应支持默认 PostgreSQL 与 Citus 数据库类型', () => {
    expect(new ProfiledDDLStrategy('postgresql').getDatabaseType()).toBe('postgresql');
    expect(new ProfiledDDLStrategy('postgresql-citus').getDatabaseType()).toBe('postgresql-citus');
  });

  it('应生成包含 identity、默认值和注释的 DDL', () => {
    const strategy = new ProfiledDDLStrategy('postgresql');
    const fields: NormalizedField[] = [
      {
        name: 'id',
        type: 'int',
        comment: '主键',
        nullable: false,
        defaultKind: 'auto_increment',
        defaultValue: '',
        onUpdate: 'none',
      },
      {
        name: 'updated_at',
        type: 'timestamp',
        comment: '更新时间',
        nullable: false,
        defaultKind: 'current_timestamp',
        defaultValue: '',
        onUpdate: 'current_timestamp',
      },
      {
        name: 'nickname',
        type: 'varchar(50)',
        comment: "昵称'别名",
        nullable: true,
        defaultKind: 'constant',
        defaultValue: "O'Reilly",
        onUpdate: 'none',
      },
    ];

    const ddl = strategy.generateTableDDL('public.users', "用户'表", fields);

    expect(ddl).toContain('CREATE TABLE public.users');
    expect(ddl).toContain('id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL');
    expect(ddl).toContain('updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP');
    expect(ddl).toContain("nickname VARCHAR(50) DEFAULT 'O''Reilly'");
    expect(ddl).toContain("COMMENT ON TABLE public.users IS '用户''表'");
    expect(ddl).toContain("COMMENT ON COLUMN public.users.nickname IS '昵称''别名'");
  });
});
