import type { DatabaseType } from '@ddlbuilder/shared-types';

export type CommentChannel = 'inline' | 'comment-on' | 'extended-property';

export interface DialectProfile {
  identityClause: string;
  uuidFunction: string;
  nowFunction: (canonicalType: string) => string;
  /** 列定义片段拼接顺序；hive 无默认值概念，只输出 nullability */
  clauseOrder: Array<'identity' | 'nullability' | 'default'>;
  /** 可空列是否显式输出 NULL */
  explicitNull: boolean;
  commentChannel: CommentChannel;
}

const constantNow = (expression: string) => () => expression;

const oracleNow = (canonicalType: string) =>
  canonicalType === 'date' ? 'SYSDATE' : 'SYSTIMESTAMP';

const mysqlLike: DialectProfile = {
  identityClause: 'AUTO_INCREMENT',
  uuidFunction: '(UUID())',
  nowFunction: constantNow('CURRENT_TIMESTAMP'),
  clauseOrder: ['identity', 'nullability', 'default'],
  explicitNull: true,
  commentChannel: 'inline',
};

const postgresLike: DialectProfile = {
  identityClause: 'GENERATED BY DEFAULT AS IDENTITY',
  uuidFunction: 'gen_random_uuid()',
  nowFunction: constantNow('CURRENT_TIMESTAMP'),
  clauseOrder: ['identity', 'nullability', 'default'],
  explicitNull: false,
  commentChannel: 'comment-on',
};

export const DIALECT_PROFILES: Record<DatabaseType, DialectProfile> = {
  mysql: mysqlLike,
  mariadb: mysqlLike,
  tidb: mysqlLike,
  oceanbase: mysqlLike,
  gbase: mysqlLike,
  polardb: mysqlLike,
  postgresql: postgresLike,
  'postgresql-citus': postgresLike,
  kingbase: postgresLike,
  gaussdb: postgresLike,
  sqlserver: {
    identityClause: 'IDENTITY(1,1)',
    uuidFunction: 'NEWID()',
    nowFunction: constantNow('GETDATE()'),
    clauseOrder: ['identity', 'nullability', 'default'],
    explicitNull: true,
    commentChannel: 'extended-property',
  },
  oracle: {
    identityClause: 'GENERATED BY DEFAULT AS IDENTITY',
    uuidFunction: 'SYS_GUID()',
    nowFunction: oracleNow,
    clauseOrder: ['identity', 'default', 'nullability'],
    explicitNull: false,
    commentChannel: 'comment-on',
  },
  'oceanbase-oracle': {
    identityClause: 'GENERATED BY DEFAULT AS IDENTITY',
    uuidFunction: 'SYS_GUID()',
    nowFunction: oracleNow,
    clauseOrder: ['identity', 'default', 'nullability'],
    explicitNull: false,
    commentChannel: 'comment-on',
  },
  dm: {
    identityClause: 'IDENTITY(1,1)',
    uuidFunction: 'SYS_GUID()',
    nowFunction: constantNow('SYSDATE'),
    clauseOrder: ['identity', 'nullability', 'default'],
    explicitNull: true,
    commentChannel: 'comment-on',
  },
  hive: {
    identityClause: '',
    uuidFunction: '',
    nowFunction: constantNow(''),
    clauseOrder: ['nullability'],
    explicitNull: true,
    commentChannel: 'inline',
  },
};
