import { OracleStrategy } from './OracleStrategy';

/**
 * OceanBase Oracle 模式 DDL 策略
 *
 * OceanBase 在 Oracle 模式下兼容 Oracle 数据库语法
 * 使用 GENERATED BY DEFAULT AS IDENTITY、COMMENT ON 语句等
 *
 * 参考: https://en.oceanbase.com/docs/common-oceanbase-database-10000000001103416
 */
export class OceanBaseOracleStrategy extends OracleStrategy {
  getDatabaseType(): 'oceanbase-oracle' {
    return 'oceanbase-oracle';
  }

  // 完全继承 OracleStrategy，无需重写任何方法
}
