import type { DatabaseType, NormalizedField, SqlFormatMode } from '@ddlbuilder/shared-types';
import {
  getCanonicalBaseType,
  supportsAutoIncrement,
  supportsDefaultCurrentTimestamp,
  supportsUuidDefault,
  formatConstantDefault,
  escapeSingleQuotes,
  parseFieldType,
} from '../utils/databaseTypeMapping';
import { AbstractDDLStrategy } from './AbstractDDLStrategy';
import type { ConfiguredTableDDL, TableFeatureConfig } from '../interfaces/DDLStrategy';
import { buildCitusShardingDDL } from '../utils/tableFeatures';

export class PostgresStrategy extends AbstractDDLStrategy {
  private readonly databaseType: DatabaseType;

  constructor(databaseType: DatabaseType = 'postgresql') {
    super();
    this.databaseType = databaseType;
  }

  getDatabaseType(): DatabaseType {
    return this.databaseType;
  }

  override applyTableFeatures(
    tableName: string,
    tableDDL: string,
    config: TableFeatureConfig,
  ): ConfiguredTableDDL {
    const configured = super.applyTableFeatures(tableName, tableDDL, config);
    if (this.databaseType !== 'postgresql-citus' || !config.citusShardingConfig) {
      return configured;
    }
    return {
      ...configured,
      trailingStatements: [
        ...configured.trailingStatements,
        buildCitusShardingDDL(tableName, config.citusShardingConfig),
      ],
    };
  }

  generateTableDDL(
    tableName: string,
    tableComment: string,
    fields: NormalizedField[],
    _tableMiscConfig?: undefined,
    sqlFormatMode: SqlFormatMode = 'compact',
  ): string {
    const typeMapper = this.createTypeMapper();
    const columns = fields.map((field) => {
      const parsedType = parseFieldType(field.type);
      const type = typeMapper.mapType(parsedType);
      const base = getCanonicalBaseType(field.type);

      const identity =
        field.defaultKind === 'auto_increment' &&
        supportsAutoIncrement(this.getDatabaseType(), base)
          ? ' GENERATED BY DEFAULT AS IDENTITY'
          : '';

      const nullableClause = field.nullable ? '' : ' NOT NULL';

      let def = '';
      if (field.defaultKind === 'constant') {
        def = formatConstantDefault(base, field.defaultValue);
      } else if (
        field.defaultKind === 'current_timestamp' &&
        supportsDefaultCurrentTimestamp(this.getDatabaseType(), base)
      ) {
        def = ' DEFAULT CURRENT_TIMESTAMP';
      } else if (field.defaultKind === 'uuid' && supportsUuidDefault(base)) {
        def = ' DEFAULT gen_random_uuid()';
      }

      return {
        name: this.formatFieldName(field.name),
        body: `${type}${identity}${nullableClause}${def}`,
      };
    });
    const columnLines = this.renderColumnDefinitions(columns, sqlFormatMode);

    const qualifiedTableName = this.formatTableName(tableName);
    const statements: string[] = [
      `CREATE TABLE ${qualifiedTableName} (\n${columnLines.join(',\n')}\n);`,
    ];

    if (tableComment.trim()) {
      statements.push(
        `COMMENT ON TABLE ${qualifiedTableName} IS '${escapeSingleQuotes(tableComment.trim())}';`,
      );
    }

    statements.push(...this.generateColumnCommentsDDL(tableName, fields));

    return statements.join('\n');
  }
}
