import type { ParsedFieldType } from '@ddlbuilder/shared-types';
import { expandDatabaseFamilies } from '../utils/databaseFamily.js';

export type TypeMappingRule =
  | { transform: (parsed: ParsedFieldType) => string }
  | { mapping: string; maxArgs?: number; defaultArgs?: string[]; suffix?: string };

export interface DatabaseTypeMapping {
  [canonicalType: string]: TypeMappingRule;
}

const FAMILY_TYPE_MAPPINGS: Record<string, DatabaseTypeMapping> = {
  mysql: {
    varchar: { mapping: 'varchar', defaultArgs: ['255'] },
    nvarchar: { mapping: 'varchar', defaultArgs: ['255'] },
    char: { mapping: 'char', defaultArgs: ['1'] },
    nchar: { mapping: 'char', defaultArgs: ['1'] },
    text: { mapping: 'text' },
    mediumtext: { mapping: 'mediumtext' },
    longtext: { mapping: 'longtext' },
    int: { mapping: 'int' },
    tinyint: { mapping: 'tinyint', defaultArgs: ['1'] },
    smallint: { mapping: 'smallint' },
    bigint: { mapping: 'bigint' },
    decimal: { mapping: 'decimal', defaultArgs: ['10', '3'] },
    float: { mapping: 'float', defaultArgs: ['10', '2'] },
    double: { mapping: 'double' },
    real: { mapping: 'double' },
    date: { mapping: 'date' },
    datetime: { mapping: 'datetime', maxArgs: 1 },
    datetime2: { mapping: 'datetime', maxArgs: 1 },
    timestamp: { mapping: 'timestamp', maxArgs: 1 },
    time: { mapping: 'time', maxArgs: 1 },
    boolean: { mapping: 'tinyint', defaultArgs: ['1'] },
    bit: { mapping: 'bit', defaultArgs: ['1'] },
    json: { mapping: 'json' },
    jsonb: { mapping: 'json' },
    blob: { mapping: 'blob' },
    varbinary: { mapping: 'varbinary', maxArgs: 1 },
    uuid: { mapping: 'char', defaultArgs: ['36'] },
    serial: {
      transform: (_parsed) => 'BIGINT UNSIGNED AUTO_INCREMENT',
    },
  },
  postgresql: {
    varchar: { mapping: 'varchar', maxArgs: 1 },
    nvarchar: { mapping: 'varchar', maxArgs: 1 },
    char: { mapping: 'char', maxArgs: 1 },
    nchar: { mapping: 'char', maxArgs: 1 },
    text: { mapping: 'text' },
    mediumtext: { mapping: 'text' },
    longtext: { mapping: 'text' },
    int: { mapping: 'integer' },
    smallint: { mapping: 'smallint' },
    tinyint: { mapping: 'smallint' },
    bigint: { mapping: 'bigint' },
    decimal: { mapping: 'numeric', defaultArgs: ['10', '3'] },
    float: { mapping: 'double precision' },
    double: { mapping: 'double precision' },
    real: { mapping: 'real' },
    date: { mapping: 'date' },
    datetime: { mapping: 'timestamp', maxArgs: 1 },
    timestamp: { mapping: 'timestamp', maxArgs: 1 },
    timestamptz: { mapping: 'timestamp', maxArgs: 1, suffix: 'WITH TIME ZONE' },
    time: { mapping: 'time', maxArgs: 1, suffix: 'WITHOUT TIME ZONE' },
    timetz: { mapping: 'time', maxArgs: 1, suffix: 'WITH TIME ZONE' },
    boolean: { mapping: 'boolean' },
    bit: { mapping: 'boolean' },
    json: { mapping: 'jsonb' },
    jsonb: { mapping: 'jsonb' },
    blob: { mapping: 'bytea' },
    varbinary: { mapping: 'bytea' },
    uuid: { mapping: 'uuid' },
    serial: { mapping: 'serial' },
    bigserial: { mapping: 'bigserial' },
    xml: { mapping: 'xml' },
  },

  sqlserver: {
    varchar: { mapping: 'varchar', defaultArgs: ['255'] },
    nvarchar: { mapping: 'nvarchar', defaultArgs: ['255'] },
    char: { mapping: 'char', defaultArgs: ['1'] },
    nchar: { mapping: 'nchar', defaultArgs: ['1'] },
    text: { mapping: 'nvarchar', defaultArgs: ['MAX'] },
    mediumtext: { mapping: 'nvarchar', defaultArgs: ['MAX'] },
    longtext: { mapping: 'nvarchar', defaultArgs: ['MAX'] },
    int: { mapping: 'int' },
    smallint: { mapping: 'smallint' },
    tinyint: { mapping: 'tinyint' },
    bigint: { mapping: 'bigint' },
    decimal: { mapping: 'decimal', defaultArgs: ['10', '3'] },
    float: { mapping: 'float', defaultArgs: ['53'] },
    double: { mapping: 'float', defaultArgs: ['53'] },
    real: { mapping: 'real' },
    date: { mapping: 'date' },
    datetime: { mapping: 'datetime2', maxArgs: 1 },
    datetime2: { mapping: 'datetime2', maxArgs: 1 },
    datetimeoffset: { mapping: 'datetimeoffset', defaultArgs: ['7'] },
    timestamp: { mapping: 'datetime2', maxArgs: 1 },
    time: { mapping: 'time', maxArgs: 1 },
    timetz: { mapping: 'time', maxArgs: 1 },
    boolean: { mapping: 'bit' },
    bit: { mapping: 'bit' },
    json: { mapping: 'nvarchar', defaultArgs: ['MAX'] },
    jsonb: { mapping: 'nvarchar', defaultArgs: ['MAX'] },
    blob: { mapping: 'varbinary', defaultArgs: ['MAX'] },
    varbinary: { mapping: 'varbinary', defaultArgs: ['MAX'] },
    uuid: { mapping: 'uniqueidentifier' },
    xml: { mapping: 'xml' },
    serial: {
      transform: (_parsed) => 'BIGINT IDENTITY(1,1)',
    },
  },

  oracle: {
    varchar: { mapping: 'varchar2', defaultArgs: ['100'] },
    nvarchar: { mapping: 'nvarchar2', defaultArgs: ['100'] },
    char: { mapping: 'char', defaultArgs: ['1'] },
    nchar: { mapping: 'nchar', defaultArgs: ['1'] },
    text: { mapping: 'clob' },
    mediumtext: { mapping: 'clob' },
    longtext: { mapping: 'clob' },
    int: { mapping: 'number', defaultArgs: ['10'] },
    smallint: { mapping: 'number', defaultArgs: ['5'] },
    tinyint: { mapping: 'number', defaultArgs: ['3'] },
    bigint: { mapping: 'number', defaultArgs: ['19'] },
    decimal: { mapping: 'number', defaultArgs: ['10', '2'] },
    float: { mapping: 'float', maxArgs: 1 },
    double: { mapping: 'binary_double' },
    real: { mapping: 'binary_float' },
    date: { mapping: 'date' },
    datetime: { mapping: 'timestamp', maxArgs: 1 },
    datetime2: { mapping: 'timestamp', maxArgs: 1 },
    timestamp: { mapping: 'timestamp', maxArgs: 1 },
    timestamptz: { mapping: 'timestamp', maxArgs: 1, suffix: 'WITH TIME ZONE' },
    time: { mapping: 'timestamp', maxArgs: 1 },
    timetz: { mapping: 'timestamp', maxArgs: 1 },
    boolean: { mapping: 'number', defaultArgs: ['1'] },
    bit: { mapping: 'number', defaultArgs: ['1'] },
    json: { mapping: 'clob' },
    jsonb: { mapping: 'clob' },
    blob: { mapping: 'blob' },
    varbinary: { mapping: 'raw', defaultArgs: ['100'] },
    uuid: { mapping: 'char', defaultArgs: ['36'] },
    xml: { mapping: 'xmltype' },
    serial: {
      transform: (_parsed) => 'NUMBER GENERATED ALWAYS AS IDENTITY',
    },
  },

  dm: {
    // 字符串类型
    varchar: { mapping: 'varchar', defaultArgs: ['255'] },
    nvarchar: { mapping: 'varchar', defaultArgs: ['255'] },
    char: { mapping: 'char', defaultArgs: ['1'] },
    nchar: { mapping: 'char', defaultArgs: ['1'] },
    text: { mapping: 'clob' },
    mediumtext: { mapping: 'clob' },
    longtext: { mapping: 'clob' },

    // 整数类型
    int: { mapping: 'int' },
    tinyint: { mapping: 'tinyint', defaultArgs: ['1'] },
    smallint: { mapping: 'smallint' },
    bigint: { mapping: 'bigint' },
    decimal: { mapping: 'number', defaultArgs: ['10', '2'] },
    double: { mapping: 'double' },
    float: { mapping: 'float', defaultArgs: ['10', '2'] },
    real: { mapping: 'real' },

    // 日期时间类型（达梦的 DATE 包含时分秒）
    date: { mapping: 'date' },
    datetime: { mapping: 'timestamp', maxArgs: 1 },
    datetime2: { mapping: 'timestamp', maxArgs: 1 },
    timestamp: { mapping: 'timestamp', maxArgs: 1 },
    timestamptz: { mapping: 'timestamp', maxArgs: 1, suffix: 'WITH TIME ZONE' },
    time: { mapping: 'time', maxArgs: 1 },
    timetz: { mapping: 'time', maxArgs: 1 },

    // 布尔类型（达梦使用 NUMBER(1)）
    boolean: { mapping: 'number', defaultArgs: ['1'] },
    bit: { mapping: 'bit', defaultArgs: ['1'] },

    // 大对象类型
    blob: { mapping: 'blob' },
    varbinary: { mapping: 'varbinary', maxArgs: 1 },

    // UUID 类型
    uuid: { mapping: 'char', defaultArgs: ['36'] },

    // 自增列类型
    serial: {
      transform: (_parsed) => 'BIGINT IDENTITY(1,1)',
    },

    // JSON 类型
    json: { mapping: 'json' },
    jsonb: { mapping: 'json' },
  },
};

// Hive 数据仓库类型映射
FAMILY_TYPE_MAPPINGS.hive = {
  string: { mapping: 'STRING' },
  varchar: { transform: () => 'STRING' },
  nvarchar: { transform: () => 'STRING' },
  char: { transform: () => 'STRING' },
  nchar: { transform: () => 'STRING' },
  text: { transform: () => 'STRING' },
  mediumtext: { transform: () => 'STRING' },
  longtext: { transform: () => 'STRING' },
  int: { mapping: 'INT' },
  tinyint: { mapping: 'TINYINT' },
  smallint: { mapping: 'SMALLINT' },
  bigint: { mapping: 'BIGINT' },
  decimal: { mapping: 'DECIMAL', defaultArgs: ['10', '3'] },
  float: { mapping: 'FLOAT' },
  double: { mapping: 'DOUBLE' },
  real: { mapping: 'DOUBLE' },
  date: { mapping: 'DATE' },
  datetime: { mapping: 'TIMESTAMP' },
  datetime2: { mapping: 'TIMESTAMP' },
  timestamp: { mapping: 'TIMESTAMP' },
  time: { transform: () => 'STRING' },
  boolean: { mapping: 'BOOLEAN' },
  bit: { mapping: 'BOOLEAN' },
  json: { transform: () => 'STRING' },
  jsonb: { transform: () => 'STRING' },
  blob: { mapping: 'BINARY' },
  varbinary: { mapping: 'BINARY' },
  uuid: { transform: () => 'STRING' },
  serial: { mapping: 'INT' },
};

export const TYPE_MAPPINGS = expandDatabaseFamilies({
  mysql: FAMILY_TYPE_MAPPINGS.mysql,
  postgresql: FAMILY_TYPE_MAPPINGS.postgresql,
  sqlserver: FAMILY_TYPE_MAPPINGS.sqlserver,
  oracle: FAMILY_TYPE_MAPPINGS.oracle,
  dm: FAMILY_TYPE_MAPPINGS.dm,
  hive: FAMILY_TYPE_MAPPINGS.hive,
});
