import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { reportError } from '../utils/errorReporter';

export interface ChangelogEntry {
  version: string;
  date: string;
  content: string;
  title?: string;
}

export interface ChangelogData {
  title: string;
  description: string;
  entries: ChangelogEntry[];
}

export type ChangelogLocale = 'zh-CN' | 'en-US';

const CHANGELOG_LOCALE_CONFIG: Record<
  ChangelogLocale,
  {
    inputPath: string;
    fallbackTitle: string;
    fallbackDescription: string;
    fallbackEmptyContent: string;
  }
> = {
  'zh-CN': {
    inputPath: '../../public/CHANGELOG_zh-CN.md',
    fallbackTitle: '更新日志',
    fallbackDescription: '',
    fallbackEmptyContent: '无更新内容',
  },
  'en-US': {
    inputPath: '../../public/CHANGLOG_en-US.md',
    fallbackTitle: 'Changelog',
    fallbackDescription: '',
    fallbackEmptyContent: 'No updates',
  },
};

function sortEntriesByVersion(entries: ChangelogEntry[]) {
  return entries.sort((a, b) => {
    // Sort by version descending (latest first)
    const aParts = a.version.split('.').map(Number);
    const bParts = b.version.split('.').map(Number);

    for (let i = 0; i < Math.max(aParts.length, bParts.length); i++) {
      const aVal = aParts[i] || 0;
      const bVal = bParts[i] || 0;
      if (aVal !== bVal) {
        return bVal - aVal;
      }
    }
    return 0;
  });
}

function parseChangelogByLocale(locale: ChangelogLocale): ChangelogData {
  const config = CHANGELOG_LOCALE_CONFIG[locale];
  const changelogPath = path.resolve(__dirname, config.inputPath);
  const fileContent = fs.readFileSync(changelogPath, 'utf8');

  const { data: frontMatter, content } = matter(fileContent);

  const versionRegex = /^## \[([0-9.]+)\] - (.+)$/gm;
  const matches = [...content.matchAll(versionRegex)];
  const entries: ChangelogEntry[] = [];

  matches.forEach((match, index) => {
    const version = match[1];
    const date = match[2];

    const startIndex = (match.index ?? 0) + match[0].length;
    const nextMatch = matches[index + 1];
    const endIndex = nextMatch?.index ?? content.length;
    const versionContent = content.substring(startIndex, endIndex).trim();

    entries.push({
      version,
      date,
      content: versionContent || config.fallbackEmptyContent,
    });
  });

  return {
    title: frontMatter.title || config.fallbackTitle,
    description: frontMatter.description || config.fallbackDescription,
    entries: sortEntriesByVersion(entries),
  };
}

export function parseChangelog(): Record<ChangelogLocale, ChangelogData> {
  return {
    'zh-CN': parseChangelogByLocale('zh-CN'),
    'en-US': parseChangelogByLocale('en-US'),
  };
}

function generateChangelogData() {
  try {
    const changelogDataMap = parseChangelog();
    const outputPath = path.resolve(__dirname, '../data/changelog.ts');

    const tsContent = `// This file is auto-generated by parseChangelog.ts
// Do not edit this file manually

export type ChangelogLocale = 'zh-CN' | 'en-US';

export interface ChangelogEntry {
  version: string;
  date: string;
  content: string;
  title?: string;
}

export interface ChangelogData {
  title: string;
  description: string;
  entries: ChangelogEntry[];
}

export const changelogDataMap: Record<ChangelogLocale, ChangelogData> = ${JSON.stringify(changelogDataMap, null, 2)} as Record<ChangelogLocale, ChangelogData>;

export function getChangelogData(locale: ChangelogLocale): ChangelogData {
  return changelogDataMap[locale];
}

export const changelogData: ChangelogData = changelogDataMap['zh-CN'];
`;

    const dataDir = path.dirname(outputPath);
    if (!fs.existsSync(dataDir)) {
      fs.mkdirSync(dataDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, tsContent, 'utf8');
    console.log('✅ Changelog data generated successfully for zh-CN and en-US');
  } catch (error) {
    reportError(error, {
      scope: 'parseChangelogScript',
      action: 'generateChangelogData',
    });
    process.exit(1);
  }
}

if (require.main === module) {
  generateChangelogData();
}
