import type { PersistedState } from '@ddlbuilder/shared-types';
import { parseFieldType, getCanonicalBaseType } from './databaseTypeMapping.js';
import { snapshotTableLabel } from './schemaSnapshot.js';

export type MigrationAssessmentLevel = 'mapped' | 'manual' | 'unsupported';

export type MigrationAssessmentItem = {
  object: string;
  source: string;
  target: string;
  level: MigrationAssessmentLevel;
  reason: string;
};

export function assessMysqlToPostgres(tables: PersistedState[]): MigrationAssessmentItem[] {
  if (!tables.length || tables.some((table) => table.dbType !== 'mysql'))
    throw new Error('Select MySQL tables for MySQL → PostgreSQL assessment.');
  const items: MigrationAssessmentItem[] = [];

  const integerTargets = new Map([
    ['tinyint', 'smallint'],
    ['smallint', 'smallint'],
    ['mediumint', 'integer'],
    ['int', 'integer'],
    ['bigint', 'bigint'],
  ]);

  for (const table of tables) {
    const name = snapshotTableLabel(table);

    if (table.objectType === 'view') {
      items.push({
        object: name,
        source: 'VIEW',
        target: '',
        level: 'unsupported',
        reason: 'view',
      });
      continue;
    }

    items.push({
      object: name,
      source: 'MySQL schema / names / collation',
      target: 'PostgreSQL schema / quoted names / collation',
      level: 'manual',
      reason: 'identifiers',
    });

    for (const field of table.rows.filter((row) => row.fieldName.trim())) {
      const parsed = parseFieldType(field.fieldType);
      const base = getCanonicalBaseType(parsed.baseType);
      const object = `${name}.${field.fieldName}`;
      let target = integerTargets.get(base) ?? '';
      let reason = 'type';
      let level: MigrationAssessmentLevel = target ? 'mapped' : 'manual';

      if (target && parsed.unsigned) {
        target =
          base === 'bigint'
            ? 'numeric(20,0)'
            : ['int', 'mediumint'].includes(base)
              ? 'bigint'
              : 'integer';
        reason = 'unsigned';
        level = 'manual';
      } else if (['decimal', 'numeric'].includes(base)) {
        target = `numeric(${parsed.args.join(',') || '10,0'})`;
        level = parsed.unsigned ? 'manual' : 'mapped';
        reason = parsed.unsigned ? 'unsigned' : 'type';
      } else if (['varchar', 'char'].includes(base)) {
        target = `${base}(${parsed.args[0] || '1'})`;
        reason = 'text';
      } else if (['text', 'tinytext', 'mediumtext', 'longtext'].includes(base)) {
        target = 'text';
        reason = 'text';
      } else if (['float', 'double', 'real'].includes(base)) {
        target =
          base === 'float' && Number(parsed.args[0] ?? 24) <= 24 ? 'real' : 'double precision';
        reason = 'float';
      } else if (base === 'date') {
        target = 'date';
        reason = 'date';
      } else if (base === 'datetime') {
        target = 'timestamp without time zone';
        reason = 'date';
      } else if (base === 'timestamp') {
        target = 'timestamp with time zone';
        reason = 'timezone';
      } else if (base === 'time') {
        target = 'interval or time';
        reason = 'duration';
      } else if (base === 'json') {
        target = 'jsonb';
        reason = 'json';
      } else if (
        ['binary', 'varbinary', 'blob', 'tinyblob', 'mediumblob', 'longblob'].includes(base)
      ) {
        target = 'bytea';
        reason = 'binary';
      } else if (base === 'enum' || base === 'set') {
        target = 'text / enum / relation';
        reason = 'enum';
      } else if (base === 'bool' || base === 'boolean') {
        target = 'boolean';
        reason = 'boolean';
      } else if (base === 'year') {
        target = 'smallint';
        reason = 'year';
      } else if (base === 'bit') {
        target = `bit(${parsed.args[0] || '1'})`;
        reason = 'binary';
      }

      if (!target) {
        level = 'unsupported';
        reason = 'unknown';
      }

      items.push({ object, source: field.fieldType, target, level, reason });

      if (field.defaultKind === 'auto_increment')
        items.push({
          object,
          source: 'AUTO_INCREMENT',
          target: 'GENERATED BY DEFAULT AS IDENTITY',
          level: 'manual',
          reason: 'identity',
        });
      else if (field.defaultKind && field.defaultKind !== 'none')
        items.push({
          object,
          source: `DEFAULT ${field.defaultValue || field.defaultKind}`,
          target: '',
          level: 'manual',
          reason: /0000-00|00-00/.test(field.defaultValue ?? '') ? 'zeroDate' : 'default',
        });

      if (field.onUpdate && field.onUpdate !== 'none')
        items.push({
          object,
          source: `ON UPDATE ${field.onUpdate}`,
          target: 'Trigger / application update',
          level: 'manual',
          reason: 'onUpdate',
        });
    }

    for (const index of table.indexes)
      items.push({
        object: `${name}.${index.name || index.kind}`,
        source: `${index.kind} (${index.fields.map((field) => field.name).join(', ')})`,
        target: '',
        level: 'manual',
        reason: 'index',
      });

    for (const relation of table.foreignKeys ?? [])
      if (!relation.logical)
        items.push({
          object: `${name}.${relation.name}`,
          source: `FOREIGN KEY → ${relation.refTable}`,
          target: '',
          level: 'manual',
          reason: 'foreignKey',
        });

    if (
      table.mysqlPartitionConfig?.enabled ||
      table.citusShardingConfig ||
      table.tableMiscConfig?.enabled
    )
      items.push({
        object: name,
        source: 'Partition / storage options',
        target: '',
        level: 'manual',
        reason: 'storage',
      });
  }

  return items;
}
