import type { DatabaseTypeMapping } from '../configs/typeMappings';

export const SQLITE_TYPE_MAPPINGS = {
  int: { mapping: 'integer' },
  smallint: { mapping: 'integer' },
  tinyint: { mapping: 'integer' },
  bigint: { mapping: 'integer' },
  boolean: { mapping: 'integer' },
  bit: { mapping: 'integer' },
  text: { mapping: 'text' },
  varchar: { mapping: 'text' },
  nvarchar: { mapping: 'text' },
  char: { mapping: 'text' },
  nchar: { mapping: 'text' },
  mediumtext: { mapping: 'text' },
  longtext: { mapping: 'text' },
  uuid: { mapping: 'text' },
  json: { mapping: 'text' },
  jsonb: { mapping: 'text' },
  date: { mapping: 'text' },
  datetime: { mapping: 'text' },
  timestamp: { mapping: 'text' },
  time: { mapping: 'text' },
  real: { mapping: 'real' },
  float: { mapping: 'real' },
  double: { mapping: 'real' },
  decimal: { mapping: 'numeric' },
  blob: { mapping: 'blob' },
  varbinary: { mapping: 'blob' },
} satisfies DatabaseTypeMapping;
