export const TYPE_ALIASES: Record<string, string> = {
  bigint: 'bigint',
  bit: 'bit',
  bool: 'boolean',
  boolean: 'boolean',
  char: 'char',
  'character varying': 'varchar',
  'character varrying': 'varchar',
  clob: 'text',
  date: 'date',
  datetime: 'datetime',
  datetime2: 'datetime2',
  'datetime offset': 'datetimeoffset',
  decimal: 'decimal',
  double: 'double',
  'double precision': 'double',
  float: 'float',
  float8: 'double',
  int: 'int',
  integer: 'int',
  int4: 'int',
  mediumtext: 'mediumtext',
  nchar: 'nchar',
  'national char': 'nchar',
  'national character': 'nchar',
  'national character varying': 'nvarchar',
  'national varchar': 'nvarchar',
  'nchar varying': 'nvarchar',
  numeric: 'decimal',
  number: 'decimal',
  nvarchar: 'nvarchar',
  real: 'real',
  serial: 'serial',
  smallint: 'smallint',
  text: 'text',
  timetz: 'timetz',
  'time with time zone': 'timetz',
  'time without time zone': 'time',
  time: 'time',
  timestamp: 'timestamp',
  'timestamp without time zone': 'timestamp',
  timestamptz: 'timestamptz',
  tinyint: 'tinyint',
  uuid: 'uuid',
  varbinary: 'varbinary',
  varchar: 'varchar',
  xml: 'xml',
  json: 'json',
  jsonb: 'jsonb',
  blob: 'blob',
  longtext: 'longtext',
  varchar2: 'varchar',
  nvarchar2: 'nvarchar',
};

export const canonicalizeBaseType = (baseType: string) => TYPE_ALIASES[baseType] ?? baseType;
