import { PostgresStrategy } from './PostgresStrategy';

/**
 * 华为 GaussDB 数据库 DDL 策略
 *
 * 华为 GaussDB 是国产分布式数据库，兼容 PostgreSQL，具有以下特性：
 * - 使用 GENERATED BY DEFAULT AS IDENTITY 自增列语法
 * - 支持分片配置
 * - 使用 COMMENT ON 语法添加注释
 * - 支持 ENCRYPTED、压缩表等特有语法
 *
 * 参考资料：
 * - https://www.huaweicloud.com/product/gaussdb.html
 */
export class GaussDbStrategy extends PostgresStrategy {
  getDatabaseType(): 'gaussdb' {
    return 'gaussdb';
  }
}
