import type { NormalizedField } from '../types';
import {
  getCanonicalBaseType,
  getOracleTimestampDefault,
  supportsAutoIncrement,
  supportsDefaultCurrentTimestamp,
  supportsUuidDefault,
  formatConstantDefault,
  escapeSingleQuotes,
  parseFieldType,
} from '../utils/databaseTypeMapping';
import { AbstractDDLStrategy } from './AbstractDDLStrategy';

export class OracleStrategy extends AbstractDDLStrategy {
  getDatabaseType(): 'oracle' {
    return 'oracle';
  }

  generateTableDDL(tableName: string, tableComment: string, fields: NormalizedField[]): string {
    const dbType = this.getDatabaseType();
    const typeMapper = this.createTypeMapper();
    const columnLines = fields.map((field) => {
      const parsedType = parseFieldType(field.type);
      const type = typeMapper.mapType(parsedType);
      const base = getCanonicalBaseType(field.type);

      // Oracle 12c+ / OceanBase Oracle 模式使用 GENERATED BY DEFAULT AS IDENTITY
      const identity =
        field.defaultKind === 'auto_increment' && supportsAutoIncrement(dbType, base)
          ? ' GENERATED BY DEFAULT AS IDENTITY'
          : '';

      let def = '';
      if (field.defaultKind === 'constant') {
        def = formatConstantDefault(base, field.defaultValue);
      } else if (
        field.defaultKind === 'current_timestamp' &&
        supportsDefaultCurrentTimestamp(dbType, base)
      ) {
        // DATE 使用 SYSDATE，TIMESTAMP 使用 SYSTIMESTAMP（符合 Oracle/OceanBase Oracle 标准）
        const timestampFn = getOracleTimestampDefault(base);
        def = ` DEFAULT ${timestampFn}`;
      } else if (field.defaultKind === 'uuid' && supportsUuidDefault(base)) {
        def = ' DEFAULT SYS_GUID()';
      }

      const nullableClause = field.nullable ? '' : ' NOT NULL';

      return `  ${this.formatFieldName(field.name)} ${type}${identity}${def}${nullableClause}`;
    });

    const qualifiedTableName = this.formatTableName(tableName);
    const statements: string[] = [
      `CREATE TABLE ${qualifiedTableName} (\n${columnLines.join(',\n')}\n);`,
    ];

    if (tableComment.trim()) {
      statements.push(
        `COMMENT ON TABLE ${qualifiedTableName} IS '${escapeSingleQuotes(tableComment.trim())}';`,
      );
    }

    statements.push(...this.generateColumnCommentsDDL(tableName, fields));

    return statements.join('\n');
  }
}
