import type { NormalizedField, IndexDefinition } from "../types";
import {
  getCanonicalBaseType,
  supportsAutoIncrement,
  supportsDefaultCurrentTimestamp,
  supportsUuidDefault,
  formatConstantDefault,
  shouldQuoteDefault,
  isLikelyFunctionOrKeyword,
  escapeSingleQuotes,
  splitQualifiedName,
  parseFieldType,
} from "../utils/databaseTypeMapping";
import { AbstractDDLStrategy } from "./AbstractDDLStrategy";

export class OracleStrategy extends AbstractDDLStrategy {
  getDatabaseType(): "oracle" {
    return "oracle";
  }

  generateTableDDL(
    tableName: string,
    tableComment: string,
    fields: NormalizedField[]
  ): string {
    const typeMapper = this.createTypeMapper();
    const columnLines = fields.map((field) => {
      const parsedType = parseFieldType(field.type);
      const type = typeMapper.mapType(parsedType);
      const base = getCanonicalBaseType(field.type);

      const identity =
        field.defaultKind === "auto_increment" &&
        supportsAutoIncrement("oracle", base)
          ? " GENERATED BY DEFAULT AS IDENTITY"
          : "";

      let def = "";
      if (field.defaultKind === "constant") {
        def = formatConstantDefault(base, field.defaultValue);
      } else if (
        field.defaultKind === "current_timestamp" &&
        supportsDefaultCurrentTimestamp("oracle", base)
      ) {
        def = " DEFAULT SYSTIMESTAMP";
      } else if (field.defaultKind === "uuid" && supportsUuidDefault(base)) {
        def = " DEFAULT SYS_GUID()";
      }

      const nullableClause = field.nullable ? "" : " NOT NULL";

      return `  ${this.formatFieldName(
        field.name
      )} ${type}${identity}${def}${nullableClause}`;
    });

    const qualifiedTableName = this.formatTableName(tableName);
    const statements: string[] = [
      `CREATE TABLE ${qualifiedTableName} (\n${columnLines.join(",\n")}\n);`,
    ];

    if (tableComment.trim()) {
      statements.push(
        `COMMENT ON TABLE ${qualifiedTableName} IS '${escapeSingleQuotes(
          tableComment.trim()
        )}';`
      );
    }

    statements.push(...this.generateColumnCommentsDDL(tableName, fields));

    return statements.join("\n");
  }
}