import type { DatabaseType, NormalizedField } from '../types';
import {
  getCanonicalBaseType,
  supportsAutoIncrement,
  supportsDefaultCurrentTimestamp,
  supportsUuidDefault,
  formatConstantDefault,
  escapeSingleQuotes,
  parseFieldType,
} from '../utils/databaseTypeMapping';
import { AbstractDDLStrategy } from './AbstractDDLStrategy';

export class PostgresStrategy extends AbstractDDLStrategy {
  constructor(private readonly databaseType: DatabaseType = 'postgresql') {
    super();
  }

  getDatabaseType(): DatabaseType {
    return this.databaseType;
  }

  generateTableDDL(tableName: string, tableComment: string, fields: NormalizedField[]): string {
    const typeMapper = this.createTypeMapper();
    const columnLines = fields.map((field) => {
      const parsedType = parseFieldType(field.type);
      const type = typeMapper.mapType(parsedType);
      const base = getCanonicalBaseType(field.type);

      const identity =
        field.defaultKind === 'auto_increment' &&
        supportsAutoIncrement(this.getDatabaseType(), base)
          ? ' GENERATED BY DEFAULT AS IDENTITY'
          : '';

      const nullableClause = field.nullable ? '' : ' NOT NULL';

      let def = '';
      if (field.defaultKind === 'constant') {
        def = formatConstantDefault(base, field.defaultValue);
      } else if (
        field.defaultKind === 'current_timestamp' &&
        supportsDefaultCurrentTimestamp(this.getDatabaseType(), base)
      ) {
        def = ' DEFAULT CURRENT_TIMESTAMP';
      } else if (field.defaultKind === 'uuid' && supportsUuidDefault(base)) {
        def = ' DEFAULT gen_random_uuid()';
      }

      return `  ${this.formatFieldName(field.name)} ${type}${identity}${nullableClause}${def}`;
    });

    const qualifiedTableName = this.formatTableName(tableName);
    const statements: string[] = [
      `CREATE TABLE ${qualifiedTableName} (\n${columnLines.join(',\n')}\n);`,
    ];

    if (tableComment.trim()) {
      statements.push(
        `COMMENT ON TABLE ${qualifiedTableName} IS '${escapeSingleQuotes(tableComment.trim())}';`,
      );
    }

    statements.push(...this.generateColumnCommentsDDL(tableName, fields));

    return statements.join('\n');
  }
}
