import type { ParsedFieldType } from "../types";

export interface TypeMappingRule {
  defaultArgs?: string[];
  mapping?: string;
  suffix?: string;
  transform?: (parsed: ParsedFieldType) => string;
}

export interface DatabaseTypeMapping {
  [canonicalType: string]: TypeMappingRule;
}

export const TYPE_MAPPINGS: Record<string, DatabaseTypeMapping> = {
  mysql: {
    varchar: { mapping: "varchar", defaultArgs: ["255"] },
    nvarchar: { mapping: "varchar", defaultArgs: ["255"] },
    char: { mapping: "char", defaultArgs: ["1"] },
    nchar: { mapping: "char", defaultArgs: ["1"] },
    text: { mapping: "text" },
    mediumtext: { mapping: "mediumtext" },
    longtext: { mapping: "longtext" },
    int: { mapping: "int" },
    tinyint: { mapping: "tinyint", defaultArgs: ["1"] },
    smallint: { mapping: "smallint" },
    bigint: { mapping: "bigint" },
    decimal: { mapping: "decimal", defaultArgs: ["10", "3"] },
    numeric: { mapping: "decimal", defaultArgs: ["10", "3"] },
    float: { mapping: "float", defaultArgs: ["10", "2"] },
    double: { mapping: "double" },
    real: { mapping: "double" },
    date: { mapping: "date" },
    datetime: { mapping: "datetime" },
    datetime2: { mapping: "datetime" },
    timestamp: { mapping: "timestamp" },
    time: { mapping: "time" },
    boolean: { mapping: "tinyint", defaultArgs: ["1"] },
    bool: { mapping: "tinyint", defaultArgs: ["1"] },
    bit: { mapping: "bit", defaultArgs: ["1"] },
    json: { mapping: "json" },
    jsonb: { mapping: "json" },
    blob: { mapping: "blob" },
    varbinary: { mapping: "varbinary" },
    uuid: { mapping: "char", defaultArgs: ["36"] },
    serial: {
      transform: (parsed) => "BIGINT UNSIGNED AUTO_INCREMENT"
    },
  },

  postgresql: {
    varchar: { mapping: "varchar" },
    nvarchar: { mapping: "varchar" },
    char: { mapping: "char" },
    nchar: { mapping: "char" },
    text: { mapping: "text" },
    mediumtext: { mapping: "text" },
    longtext: { mapping: "text" },
    int: { mapping: "integer" },
    integer: { mapping: "integer" },
    smallint: { mapping: "smallint" },
    tinyint: { mapping: "smallint" },
    bigint: { mapping: "bigint" },
    decimal: { mapping: "numeric", defaultArgs: ["10", "3"] },
    numeric: { mapping: "numeric", defaultArgs: ["10", "3"] },
    number: { mapping: "numeric", defaultArgs: ["10", "3"] },
    float: { mapping: "double precision" },
    double: { mapping: "double precision" },
    real: { mapping: "real" },
    date: { mapping: "date" },
    datetime: { mapping: "timestamp" },
    timestamp: { mapping: "timestamp" },
    timestamptz: { mapping: "timestamp", suffix: "WITH TIME ZONE" },
    time: { mapping: "time", suffix: "WITHOUT TIME ZONE" },
    timetz: { mapping: "time", suffix: "WITH TIME ZONE" },
    boolean: { mapping: "boolean" },
    bool: { mapping: "boolean" },
    bit: { mapping: "boolean" },
    json: { mapping: "jsonb" },
    jsonb: { mapping: "jsonb" },
    blob: { mapping: "bytea" },
    varbinary: { mapping: "bytea" },
    uuid: { mapping: "uuid" },
    serial: { mapping: "serial" },
    bigserial: { mapping: "bigserial" },
    xml: { mapping: "xml" },
  },

  sqlserver: {
    varchar: { mapping: "varchar", defaultArgs: ["255"] },
    nvarchar: { mapping: "nvarchar", defaultArgs: ["255"] },
    char: { mapping: "char", defaultArgs: ["1"] },
    nchar: { mapping: "nchar", defaultArgs: ["1"] },
    text: { mapping: "nvarchar", defaultArgs: ["MAX"] },
    mediumtext: { mapping: "nvarchar", defaultArgs: ["MAX"] },
    longtext: { mapping: "nvarchar", defaultArgs: ["MAX"] },
    clob: { mapping: "nvarchar", defaultArgs: ["MAX"] },
    int: { mapping: "int" },
    integer: { mapping: "int" },
    smallint: { mapping: "smallint" },
    tinyint: { mapping: "tinyint" },
    bigint: { mapping: "bigint" },
    decimal: { mapping: "decimal", defaultArgs: ["10", "3"] },
    numeric: { mapping: "decimal", defaultArgs: ["10", "3"] },
    float: { mapping: "float", defaultArgs: ["53"] },
    double: { mapping: "float", defaultArgs: ["53"] },
    real: { mapping: "real" },
    date: { mapping: "date" },
    datetime: { mapping: "datetime2" },
    datetime2: { mapping: "datetime2" },
    datetimeoffset: { mapping: "datetimeoffset", defaultArgs: ["7"] },
    timestamp: { mapping: "datetime2" },
    time: { mapping: "time" },
    timetz: { mapping: "time" },
    boolean: { mapping: "bit" },
    bool: { mapping: "bit" },
    bit: { mapping: "bit" },
    json: { mapping: "nvarchar", defaultArgs: ["MAX"] },
    jsonb: { mapping: "nvarchar", defaultArgs: ["MAX"] },
    blob: { mapping: "varbinary", defaultArgs: ["MAX"] },
    varbinary: { mapping: "varbinary", defaultArgs: ["MAX"] },
    uuid: { mapping: "uniqueidentifier" },
    xml: { mapping: "xml" },
    serial: {
      transform: (parsed) => "BIGINT IDENTITY(1,1)"
    },
  },

  oracle: {
    varchar: { mapping: "varchar2", defaultArgs: ["100"] },
    nvarchar: { mapping: "nvarchar2", defaultArgs: ["100"] },
    char: { mapping: "char", defaultArgs: ["1"] },
    nchar: { mapping: "nchar", defaultArgs: ["1"] },
    text: { mapping: "clob" },
    mediumtext: { mapping: "clob" },
    longtext: { mapping: "clob" },
    clob: { mapping: "clob" },
    int: { mapping: "number", defaultArgs: ["10"] },
    integer: { mapping: "number", defaultArgs: ["10"] },
    smallint: { mapping: "number", defaultArgs: ["5"] },
    tinyint: { mapping: "number", defaultArgs: ["3"] },
    bigint: { mapping: "number", defaultArgs: ["19"] },
    decimal: { mapping: "number", defaultArgs: ["10", "2"] },
    numeric: { mapping: "number", defaultArgs: ["10", "2"] },
    number: { mapping: "number", defaultArgs: ["10", "2"] },
    float: { mapping: "float" },
    double: { mapping: "binary_double" },
    real: { mapping: "binary_float" },
    date: { mapping: "date" },
    datetime: { mapping: "timestamp" },
    datetime2: { mapping: "timestamp" },
    timestamp: { mapping: "timestamp" },
    timestamptz: { mapping: "timestamp", suffix: "WITH TIME ZONE" },
    time: { mapping: "timestamp" },
    timetz: { mapping: "timestamp" },
    boolean: { mapping: "number", defaultArgs: ["1"] },
    bool: { mapping: "number", defaultArgs: ["1"] },
    bit: { mapping: "number", defaultArgs: ["1"] },
    json: { mapping: "clob" },
    jsonb: { mapping: "clob" },
    blob: { mapping: "blob" },
    varbinary: { mapping: "raw", defaultArgs: ["100"] },
    uuid: { mapping: "char", defaultArgs: ["36"] },
    xml: { mapping: "xmltype" },
    serial: {
      transform: (parsed) => "NUMBER GENERATED ALWAYS AS IDENTITY"
    },
  },
};