import { DatabaseSync } from 'node:sqlite';
import { stripTypeScriptTypes } from 'node:module';
import { runInNewContext } from 'node:vm';
import { describe, expect, it } from 'vitest';
import { sql, asc, desc } from 'drizzle-orm';
import * as sqliteCore from 'drizzle-orm/sqlite-core';
import type { SQLiteTable } from 'drizzle-orm/sqlite-core';
import type { PersistedState } from '@ddlbuilder/shared-types';
import { instantiateBusinessModule } from '../utils/businessModules';
import { buildSqliteProject, buildSqliteTable } from '../utils/sqliteSchema';
import { snapshotFields } from '../utils/schemaSnapshot';
import { buildDDL, buildDCL, buildViewDDL } from '../utils/ddlGenerators';
import { buildORM } from '../utils/ormGenerators';
import { generateAlterDDL } from '../utils/alter-ddl/generateAlterDDL';
import { diffPersistedState } from '../utils/tableDiff';

function tables(): PersistedState[] {
  return instantiateBusinessModule('rbac', 'mysql', '', 'integer').map((table) => ({
    ...table,
    dbType: 'sqlite',
  }));
}

function evaluateSchema(source: string): SQLiteTable[] {
  const names = [...source.matchAll(/export const (\w+)/g)].map((match) => match[1]);
  const code = source.replace(/^import .*\n/gm, '').replaceAll('export const ', 'const ');
  const stripped = stripTypeScriptTypes(`${code}\n[${names.join(',')}];`);

  // SAFETY: source is generated by buildSqliteProject above; the evaluation returns only its SQLiteTable exports.
  return runInNewContext(stripped, { ...sqliteCore, sql, asc, desc }) as SQLiteTable[];
}

describe('SQLite and D1 exports', () => {
  it('executes complete initialization and enforces primary, unique and foreign keys in SQLite', () => {
    const project = buildSqliteProject(tables());
    const db = new DatabaseSync(':memory:');

    try {
      db.exec('PRAGMA foreign_keys = ON;');
      db.exec(project.sql);
      db.exec(
        "INSERT INTO users(username) VALUES ('alice'); INSERT INTO roles(code,name) VALUES ('admin','Admin'); INSERT INTO user_roles(user_id,role_id) VALUES (1,1);",
      );
      expect(db.prepare('SELECT id FROM users').get()).toEqual({ id: 1 });
      expect(() => db.exec("INSERT INTO users(username) VALUES ('alice')")).toThrow('UNIQUE');
      expect(() => db.exec('INSERT INTO user_roles(user_id,role_id) VALUES (99,1)')).toThrow(
        'FOREIGN KEY',
      );
      expect(() => db.exec('INSERT INTO user_roles(user_id,role_id) VALUES (1,1)')).toThrow(
        'UNIQUE',
      );
      expect(project.sql).not.toContain('ALTER TABLE');
      expect(project.sql).not.toContain('COMMENT ON');
    } finally {
      db.close();
    }
  });
  it('evaluates generated Drizzle models with matching keys and relationships', () => {
    const project = buildSqliteProject(tables());
    const generated = evaluateSchema(project.schema);
    const configs = generated.map(sqliteCore.getTableConfig);
    expect(configs.map((config) => config.name)).toEqual(tables().map((table) => table.tableName));
    const junction = configs.find((config) => config.name === 'user_roles');
    expect(junction?.foreignKeys).toHaveLength(2);
    expect(junction?.uniqueConstraints[0].columns.map((column) => column.name)).toEqual([
      'user_id',
      'role_id',
    ]);
    expect(configs[0].columns.find((column) => column.name === 'id')?.primary).toBe(true);
  });
  it('preserves composite keys, ordered indexes, quoted names, defaults and self references', () => {
    const table = tables()[0];
    table.tableName = 'user"records';
    table.rows[0].defaultKind = 'none';
    table.rows[1].defaultKind = 'constant';
    table.rows[1].defaultValue = "O'Reilly";
    table.indexes = [
      {
        id: 'pk',
        name: 'pk',
        kind: 'primary',
        fields: [
          { name: 'id', direction: 'ASC' },
          { name: 'username', direction: 'ASC' },
        ],
      },
      {
        id: 'idx',
        name: 'name_index',
        kind: 'unique_index',
        fields: [{ name: 'username', direction: 'DESC' }],
      },
    ];
    table.foreignKeys = [
      {
        id: 'self',
        name: 'self',
        fields: ['id', 'username'],
        refTable: table.tableName,
        refFields: ['id', 'username'],
        onDelete: 'CASCADE',
      },
    ];
    const project = buildSqliteProject([table]);
    const db = new DatabaseSync(':memory:');

    try {
      db.exec(project.sql);
      expect(db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all()).toEqual([
        { name: table.tableName },
      ]);
    } finally {
      db.close();
    }

    const config = sqliteCore.getTableConfig(evaluateSchema(project.schema)[0]);
    expect(config.primaryKeys[0].columns.map((column) => column.name)).toEqual(['id', 'username']);
    expect(config.foreignKeys[0].reference().foreignColumns.map((column) => column.name)).toEqual([
      'id',
      'username',
    ]);
    expect(project.sql).toContain("DEFAULT 'O''Reilly'");
    expect(project.sql).toContain('"username" DESC');
  });
  it('preserves cyclic foreign keys without initialization errors', () => {
    const models = tables();
    models[0].foreignKeys = [
      { id: 'cycle', name: 'cycle', fields: ['id'], refTable: 'user_roles', refFields: ['id'] },
    ];
    const generated = evaluateSchema(buildSqliteProject(models).schema);
    expect(sqliteCore.getTableConfig(generated[0]).foreignKeys[0].reference().foreignTable).toBe(
      generated[3],
    );
    expect(sqliteCore.getTableConfig(generated[3]).foreignKeys[0].reference().foreignTable).toBe(
      generated[0],
    );
  });
  it('matches SQLite identifier quoting and ASCII-only case folding', () => {
    const table = tables()[0];
    table.rows[1].fieldName = '"username"';
    table.rows.push(
      { id: 'upper', fieldName: 'Å', fieldType: 'text', fieldComment: '', nullable: true },
      { id: 'lower', fieldName: 'å', fieldType: 'text', fieldComment: '', nullable: true },
    );
    const project = buildSqliteProject([table]);
    const db = new DatabaseSync(':memory:');

    try {
      db.exec(project.sql);
      expect(
        db
          .prepare('PRAGMA table_info(users)')
          .all()
          .map((row) => row.name),
      ).toEqual(['id', 'username', 'Å', 'å']);
    } finally {
      db.close();
    }

    expect(
      sqliteCore
        .getTableConfig(evaluateSchema(project.schema)[0])
        .columns.map((column) => column.name),
    ).toEqual(['id', 'username', 'Å', 'å']);
  });
  it('blocks partial or invalid projects and unsupported configurations', () => {
    const models = tables();
    expect(() => buildSqliteProject([models[3]])).toThrow('referenced table');
    expect(() => buildSqliteProject([models[0], models[0]])).toThrow('Duplicate');
    expect(() => buildSqliteProject([{ ...models[0], schemaName: 'public' }])).toThrow(
      'unqualified',
    );
    expect(() => buildSqliteProject([{ ...models[0], indexes: [] }])).toThrow('auto-increment');
    expect(() =>
      buildSqliteProject([
        {
          ...models[0],
          rows: models[0].rows.map((row) => ({ ...row, onUpdate: 'current_timestamp' })),
        },
      ]),
    ).toThrow('ON UPDATE');
    expect(() =>
      buildSqliteProject([
        { ...models[0], rows: [{ ...models[0].rows[0], fieldType: 'geometry' }] },
      ]),
    ).toThrow('Unsupported SQLite type');
    const input = { ...models[0], fields: snapshotFields(models[0]) };
    expect(buildDDL({ ...input, tableMiscConfig: { enabled: true } })).toContain('blocked');
    expect(buildDCL('users', ['reader'], 'sqlite')).not.toContain('GRANT SELECT');
    expect(buildViewDDL('sqlite', 'v', 'SELECT 1')).toBe('CREATE VIEW v AS\nSELECT 1;');
    expect(
      generateAlterDDL(diffPersistedState(models[0], { ...models[0], tableName: 'changed' })),
    ).toContain('Manual migration');
    expect(buildORM('prisma', input)).toContain('Select Drizzle');
    expect(buildORM('drizzle', input)).toContain('sqliteTable');
    expect(buildORM('drizzle', { ...input, dbType: 'mysql' })).toContain('blocked');
  });
  it('supports SQLite native storage classes and explicit default policies', () => {
    const model = tables()[0];

    const fields = ['int', 'text', 'real', 'blob', 'decimal', 'date', 'json'].map(
      (type, index) => ({
        name: `f${index}`,
        type,
        comment: '',
        nullable: true,
        defaultKind: 'none' as const,
        defaultValue: '',
        onUpdate: 'none' as const,
      }),
    );
    const input = { ...model, indexes: [], fields };
    expect(buildSqliteTable(input)).toContain('"f4" NUMERIC');
    expect(() =>
      buildSqliteTable({
        ...input,
        fields: [{ ...fields[0], defaultKind: 'constant', defaultValue: 'x' }],
      }),
    ).toThrow('numeric');
    expect(() =>
      buildSqliteTable({ ...input, fields: [{ ...fields[1], defaultKind: 'uuid' }] }),
    ).toThrow('UUID');
    expect(() =>
      buildSqliteTable({
        ...input,
        fields: [{ ...fields[1], defaultKind: 'expression', defaultValue: 'random()' }],
      }),
    ).toThrow('expressions');
    expect(
      buildSqliteTable({ ...input, fields: [{ ...fields[1], defaultKind: 'current_timestamp' }] }),
    ).toContain('DEFAULT CURRENT_TIMESTAMP');
  });
});
