import { describe, it, expect } from 'vitest';
import { OceanBaseOracleStrategy } from '@/strategies/OceanBaseOracleStrategy';
import type { NormalizedField } from '@/types';

describe('OceanBaseOracleStrategy', () => {
  const strategy = new OceanBaseOracleStrategy();

  it('应该返回 oceanbase-oracle 数据库类型', () => {
    expect(strategy.getDatabaseType()).toBe('oceanbase-oracle');
  });

  it('应该生成基本的 OceanBase Oracle 模式 DDL', () => {
    const fields: NormalizedField[] = [
      {
        name: 'id',
        type: 'int',
        comment: '主键ID',
        nullable: false,
        defaultKind: 'auto_increment',
        defaultValue: '',
        onUpdate: 'none',
      },
      {
        name: 'name',
        type: 'varchar(100)',
        comment: '名称',
        nullable: true,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
      {
        name: 'created_at',
        type: 'timestamp',
        comment: '创建时间',
        nullable: false,
        defaultKind: 'current_timestamp',
        defaultValue: '',
        onUpdate: 'none',
      },
    ];

    const result = strategy.generateTableDDL('users', '用户表', fields);

    // 验证基本结构
    expect(result).toContain('CREATE TABLE users');
    expect(result).toContain('id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY');
    expect(result).toContain('name VARCHAR2(100)');
    expect(result).toContain('created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL');

    // 验证注释语法（Oracle 风格）
    expect(result).toContain("COMMENT ON TABLE users IS '用户表'");
    expect(result).toContain("COMMENT ON COLUMN users.id IS '主键ID'");
  });

  it('应该支持各种整数类型（映射为 NUMBER）', () => {
    const fields: NormalizedField[] = [
      {
        name: 'tiny',
        type: 'tinyint',
        comment: '',
        nullable: false,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
      {
        name: 'small',
        type: 'smallint',
        comment: '',
        nullable: false,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
      {
        name: 'medium',
        type: 'int',
        comment: '',
        nullable: false,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
      {
        name: 'big',
        type: 'bigint',
        comment: '',
        nullable: false,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
    ];

    const result = strategy.generateTableDDL('test', '', fields);

    expect(result).toContain('tiny NUMBER(3) NOT NULL');
    expect(result).toContain('small NUMBER(5) NOT NULL');
    expect(result).toContain('medium NUMBER(10) NOT NULL');
    expect(result).toContain('big NUMBER(19) NOT NULL');
  });

  it('应该支持 DATE 和 TIMESTAMP 类型', () => {
    const fields: NormalizedField[] = [
      {
        name: 'd',
        type: 'date',
        comment: '',
        nullable: true,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
      {
        name: 'dt',
        type: 'datetime',
        comment: '',
        nullable: true,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
      {
        name: 'ts',
        type: 'timestamp',
        comment: '',
        nullable: true,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
    ];

    const result = strategy.generateTableDDL('test', '', fields);

    expect(result).toContain('d DATE');
    expect(result).toContain('dt TIMESTAMP');
    expect(result).toContain('ts TIMESTAMP');
  });

  it('应该支持 CLOB 和 BLOB 类型', () => {
    const fields: NormalizedField[] = [
      {
        name: 'c',
        type: 'clob',
        comment: '大文本',
        nullable: true,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
      {
        name: 'b',
        type: 'blob',
        comment: '二进制',
        nullable: true,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
    ];

    const result = strategy.generateTableDDL('test', '', fields);

    expect(result).toContain('c CLOB');
    expect(result).toContain('b BLOB');
    expect(result).toContain("COMMENT ON COLUMN test.c IS '大文本'");
    expect(result).toContain("COMMENT ON COLUMN test.b IS '二进制'");
  });

  it('应该支持 NUMBER 类型', () => {
    const fields: NormalizedField[] = [
      {
        name: 'price',
        type: 'number(10,2)',
        comment: '价格',
        nullable: false,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
    ];

    const result = strategy.generateTableDDL('products', '', fields);

    expect(result).toContain('price NUMBER(10, 2) NOT NULL');
  });

  it('应该支持 DECIMAL 类型（映射为 NUMBER）', () => {
    const fields: NormalizedField[] = [
      {
        name: 'amount',
        type: 'decimal(15,4)',
        comment: '金额',
        nullable: false,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
    ];

    const result = strategy.generateTableDDL('test', '', fields);

    expect(result).toContain('amount NUMBER(15, 4) NOT NULL');
  });

  it('应该支持布尔类型（使用 NUMBER(1)）', () => {
    const fields: NormalizedField[] = [
      {
        name: 'is_active',
        type: 'boolean',
        comment: '是否激活',
        nullable: false,
        defaultKind: 'constant',
        defaultValue: '1',
        onUpdate: 'none',
      },
    ];

    const result = strategy.generateTableDDL('users', '', fields);

    expect(result).toContain('is_active NUMBER(1) DEFAULT 1 NOT NULL');
  });

  it('应该支持 UUID 默认值（使用 SYS_GUID()）', () => {
    const fields: NormalizedField[] = [
      {
        name: 'trace_id',
        type: 'uuid',
        comment: '追踪ID',
        nullable: false,
        defaultKind: 'uuid',
        defaultValue: '',
        onUpdate: 'none',
      },
    ];

    const result = strategy.generateTableDDL('test', '', fields);

    expect(result).toContain('trace_id CHAR(36) DEFAULT SYS_GUID() NOT NULL');
  });

  it('应该支持常量默认值', () => {
    const fields: NormalizedField[] = [
      {
        name: 'status',
        type: 'int',
        comment: '状态',
        nullable: false,
        defaultKind: 'constant',
        defaultValue: '0',
        onUpdate: 'none',
      },
      {
        name: 'name',
        type: 'varchar(100)',
        comment: '名称',
        nullable: false,
        defaultKind: 'constant',
        defaultValue: 'anonymous',
        onUpdate: 'none',
      },
    ];

    const result = strategy.generateTableDDL('test', '', fields);

    expect(result).toContain('status NUMBER(10) DEFAULT 0 NOT NULL');
    expect(result).toContain("name VARCHAR2(100) DEFAULT 'anonymous' NOT NULL");
  });

  it('不应该支持 ON UPDATE CURRENT_TIMESTAMP', () => {
    const fields: NormalizedField[] = [
      {
        name: 'updated_at',
        type: 'timestamp',
        comment: '更新时间',
        nullable: false,
        defaultKind: 'current_timestamp',
        defaultValue: '',
        onUpdate: 'current_timestamp',
      },
    ];

    const result = strategy.generateTableDDL('test', '', fields);

    // OceanBase Oracle 模式不支持 ON UPDATE CURRENT_TIMESTAMP
    expect(result).toContain('updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL');
    expect(result).not.toContain('ON UPDATE');
  });

  it('应该支持 VARCHAR2 和 NVARCHAR2 类型', () => {
    const fields: NormalizedField[] = [
      {
        name: 'vc',
        type: 'varchar(50)',
        comment: '',
        nullable: true,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
      {
        name: 'nvc',
        type: 'nvarchar(100)',
        comment: '',
        nullable: true,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
    ];

    const result = strategy.generateTableDDL('test', '', fields);

    expect(result).toContain('vc VARCHAR2(50)');
    expect(result).toContain('nvc NVARCHAR2(100)');
  });

  it('应该支持 RAW 类型（varbinary 映射）', () => {
    const fields: NormalizedField[] = [
      {
        name: 'data',
        type: 'varbinary(200)',
        comment: '二进制数据',
        nullable: true,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
    ];

    const result = strategy.generateTableDDL('test', '', fields);

    expect(result).toContain('data RAW(200)');
  });

  it('应该支持 TEXT 类型（映射为 CLOB）', () => {
    const fields: NormalizedField[] = [
      {
        name: 'content',
        type: 'text',
        comment: '内容',
        nullable: true,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
    ];

    const result = strategy.generateTableDDL('articles', '', fields);

    expect(result).toContain('content CLOB');
  });

  it('应该支持 FLOAT 和 DOUBLE 类型', () => {
    const fields: NormalizedField[] = [
      {
        name: 'f',
        type: 'float',
        comment: '',
        nullable: true,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
      {
        name: 'd',
        type: 'double',
        comment: '',
        nullable: true,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
    ];

    const result = strategy.generateTableDDL('test', '', fields);

    expect(result).toContain('f FLOAT');
    expect(result).toContain('d BINARY_DOUBLE');
  });

  it('应该支持 TIMESTAMP WITH TIME ZONE', () => {
    const fields: NormalizedField[] = [
      {
        name: 'ts',
        type: 'timestamptz',
        comment: '时间戳带时区',
        nullable: true,
        defaultKind: 'none',
        defaultValue: '',
        onUpdate: 'none',
      },
    ];

    const result = strategy.generateTableDDL('test', '', fields);

    expect(result).toContain('ts TIMESTAMP WITH TIME ZONE');
  });

  it('DATE 应该使用 SYSDATE，TIMESTAMP 应该使用 SYSTIMESTAMP', () => {
    const fields: NormalizedField[] = [
      {
        name: 'created_date',
        type: 'date',
        comment: '创建日期',
        nullable: false,
        defaultKind: 'current_timestamp',
        defaultValue: '',
        onUpdate: 'none',
      },
      {
        name: 'created_at',
        type: 'timestamp',
        comment: '创建时间',
        nullable: false,
        defaultKind: 'current_timestamp',
        defaultValue: '',
        onUpdate: 'none',
      },
    ];

    const result = strategy.generateTableDDL('test', '', fields);

    // DATE 使用 SYSDATE（精确到秒）
    expect(result).toContain('created_date DATE DEFAULT SYSDATE NOT NULL');
    // TIMESTAMP 使用 SYSTIMESTAMP（包含小数秒和时区）
    expect(result).toContain('created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL');
  });
});
