import type { PersistedState } from '@ddlbuilder/shared-types';
import { createEmptyRow } from '@/utils/helpers';

export const EXAMPLE_USER_PROFILE_TABLE: PersistedState = {
  schemaName: '',
  tableName: 'user_profile',
  tableComment: '用户资料表',
  dbType: 'mysql',
  sqlFormatMode: 'compact',
  rows: [
    {
      ...createEmptyRow(0),
      fieldName: 'id',
      fieldType: 'BIGINT',
      fieldComment: '主键ID',
      nullable: false,
      defaultKind: 'autoIncrement',
      defaultValue: '',
      length: '',
    },
    {
      ...createEmptyRow(1),
      fieldName: 'username',
      fieldType: 'VARCHAR',
      fieldComment: '用户名',
      nullable: false,
      defaultKind: 'none',
      defaultValue: '',
      length: '50',
    },
    {
      ...createEmptyRow(2),
      fieldName: 'email',
      fieldType: 'VARCHAR',
      fieldComment: '邮箱',
      nullable: false,
      defaultKind: 'none',
      defaultValue: '',
      length: '100',
    },
    {
      ...createEmptyRow(3),
      fieldName: 'phone',
      fieldType: 'VARCHAR',
      fieldComment: '手机号',
      nullable: true,
      defaultKind: 'none',
      defaultValue: '',
      length: '20',
    },
    {
      ...createEmptyRow(4),
      fieldName: 'avatar_url',
      fieldType: 'VARCHAR',
      fieldComment: '头像URL',
      nullable: true,
      defaultKind: 'none',
      defaultValue: '',
      length: '255',
    },
    {
      ...createEmptyRow(5),
      fieldName: 'gender',
      fieldType: 'TINYINT',
      fieldComment: '性别：0-未知，1-男，2-女',
      nullable: true,
      defaultKind: 'constant',
      defaultValue: '0',
      length: '',
    },
    {
      ...createEmptyRow(6),
      fieldName: 'birth_date',
      fieldType: 'DATE',
      fieldComment: '出生日期',
      nullable: true,
      defaultKind: 'none',
      defaultValue: '',
      length: '',
    },
    {
      ...createEmptyRow(7),
      fieldName: 'status',
      fieldType: 'TINYINT',
      fieldComment: '状态：0-禁用，1-启用',
      nullable: false,
      defaultKind: 'constant',
      defaultValue: '1',
      length: '',
    },
    {
      ...createEmptyRow(8),
      fieldName: 'created_at',
      fieldType: 'TIMESTAMP',
      fieldComment: '创建时间',
      nullable: false,
      defaultKind: 'currentTimestamp',
      defaultValue: '',
      length: '',
    },
    {
      ...createEmptyRow(9),
      fieldName: 'updated_at',
      fieldType: 'TIMESTAMP',
      fieldComment: '更新时间',
      nullable: false,
      defaultKind: 'currentTimestamp',
      defaultValue: '',
      length: '',
      onUpdate: 'currentTimestamp',
    },
    ...Array.from({ length: 2 }, (_, index) => createEmptyRow(index + 10)),
  ],
  addCount: 10,
  indexInput: '',
  currentIndexFields: [],
  indexes: [
    {
      id: 'idx_pk_id',
      name: 'PRIMARY',
      type: 'primary',
      method: 'BTREE',
      fields: ['id'],
    },
    {
      id: 'idx_uk_username',
      name: 'uk_username',
      type: 'unique',
      method: 'BTREE',
      fields: ['username'],
    },
  ],
  authInput: '',
  authObjects: [],
};
