import type { PersistedState } from '@ddlbuilder/shared-types';
import { createEmptyRow } from '@/utils/helpers';

export const EXAMPLE_USER_PROFILE_TABLE: PersistedState = {
  schemaName: '',
  tableName: 'user_profile',
  tableComment: '用户资料表',
  dbType: 'mysql',
  sqlFormatMode: 'compact',
  rows: [
    {
      ...createEmptyRow(0),
      fieldName: 'id',
      fieldType: 'BIGINT',
      fieldComment: '主键ID',
      nullable: '否',
      defaultKind: '自增',
      defaultValue: '',
    },
    {
      ...createEmptyRow(1),
      fieldName: 'username',
      fieldType: 'VARCHAR(50)',
      fieldComment: '用户名',
      nullable: '否',
      defaultKind: '无',
      defaultValue: '',
    },
    {
      ...createEmptyRow(2),
      fieldName: 'email',
      fieldType: 'VARCHAR(100)',
      fieldComment: '邮箱',
      nullable: '否',
      defaultKind: '无',
      defaultValue: '',
    },
    {
      ...createEmptyRow(3),
      fieldName: 'phone',
      fieldType: 'VARCHAR(20)',
      fieldComment: '手机号',
      nullable: '是',
      defaultKind: '无',
      defaultValue: '',
    },
    {
      ...createEmptyRow(4),
      fieldName: 'avatar_url',
      fieldType: 'VARCHAR(255)',
      fieldComment: '头像URL',
      nullable: '是',
      defaultKind: '无',
      defaultValue: '',
    },
    {
      ...createEmptyRow(5),
      fieldName: 'gender',
      fieldType: 'TINYINT',
      fieldComment: '性别：0-未知，1-男，2-女',
      nullable: '是',
      defaultKind: '常量',
      defaultValue: '0',
    },
    {
      ...createEmptyRow(6),
      fieldName: 'birth_date',
      fieldType: 'DATE',
      fieldComment: '出生日期',
      nullable: '是',
      defaultKind: '无',
      defaultValue: '',
    },
    {
      ...createEmptyRow(7),
      fieldName: 'status',
      fieldType: 'TINYINT',
      fieldComment: '状态：0-禁用，1-启用',
      nullable: '否',
      defaultKind: '常量',
      defaultValue: '1',
    },
    {
      ...createEmptyRow(8),
      fieldName: 'created_at',
      fieldType: 'TIMESTAMP',
      fieldComment: '创建时间',
      nullable: '否',
      defaultKind: '当前时间',
      defaultValue: '',
    },
    {
      ...createEmptyRow(9),
      fieldName: 'updated_at',
      fieldType: 'TIMESTAMP',
      fieldComment: '更新时间',
      nullable: '否',
      defaultKind: '当前时间',
      defaultValue: '',
      onUpdate: '当前时间',
    },
    ...Array.from({ length: 2 }, (_, index) => createEmptyRow(index + 10)),
  ],
  addCount: 10,
  indexInput: '',
  currentIndexFields: [],
  indexes: [
    {
      id: 'idx_pk_id',
      name: 'PRIMARY',
      unique: false,
      isPrimary: true,
      fields: [{ name: 'id', direction: 'ASC' }],
    },
    {
      id: 'idx_uk_username',
      name: 'uk_username',
      unique: true,
      isPrimary: false,
      fields: [{ name: 'username', direction: 'ASC' }],
    },
  ],
  authInput: '',
  authObjects: [],
};
