// This file is auto-generated by parseChangelog.ts
// Do not edit this file manually

export interface ChangelogEntry {
  version: string;
  date: string;
  content: string;
  title?: string;
}

export interface ChangelogData {
  title: string;
  description: string;
  entries: ChangelogEntry[];
}

export const changelogData: ChangelogData = {
  title: '筑表师更新日志',
  description: 'DDL建表工具版本更新记录',
  entries: [
    {
      version: '0.8.0',
      date: '2025-12-29',
      content:
        '### 新增MySQL 分区表配置\n- 新增「分区配置」Tab 页，支持 MySQL、MariaDB、TiDB\n- 支持 6 种分区类型：RANGE、RANGE COLUMNS、LIST、LIST COLUMNS、HASH、KEY\n- 每种分区类型配有说明，帮助用户选择合适的分区策略\n- HASH/KEY 分区支持配置分区数量\n- RANGE/LIST 分区支持自定义分区定义\n- DDL 自动生成对应的分区语句',
    },
    {
      version: '0.7.0',
      date: '2025-12-24',
      content:
        '### 新增数据库支持\n- 新增 **MariaDB** 数据库类型支持\n- 新增 **TiDB** 数据库类型支持\n- 新增 **达梦 (Dameng)** 数据库类型支持\n- 新增 **OceanBase** 数据库支持（MySQL 模式 & Oracle 模式）\n- 新增 **PostgreSQL Citus** 数据库类型支持\n\n### Citus 分片配置\n- 新增「分片配置」Tab 页，仅在选择 PostgreSQL Citus 时显示\n- 支持配置表模式：副本表 (Reference Table) 或分片表 (Distributed Table)\n- 分片表模式下可选择分片字段\n- DDL 自动生成 `create_reference_table()` 或 `create_distributed_table()` 语句',
    },
    {
      version: '0.6.5',
      date: '2025-12-19',
      content:
        '- 修复 COMMENT 解析对转义单引号的支持，避免截断注释内容\n- Oracle 索引名按 30 字符限制生成，避免超长\n- 默认值包含 “default” 时按常量处理并正确加引号',
    },
    {
      version: '0.6.4',
      date: '2025-12-18',
      content: '- 一些微小的更新',
    },
    {
      version: '0.6.3',
      date: '2025-12-17',
      content: '- 一些微小的更新',
    },
    {
      version: '0.6.2',
      date: '2025-12-16',
      content: '- 一些微小的更新',
    },
    {
      version: '0.6.1',
      date: '2025-12-15',
      content: '- 一些微小的更新',
    },
    {
      version: '0.6.0',
      date: '2025-12-11',
      content:
        '- 索引名称显示优化：长名称自动换行，不再超出卡片边界\n- 索引名称自动截断：超过40字符时自动截断并添加哈希后缀确保唯一性\n- 新增双击编辑索引名称功能，支持自定义索引名称',
    },
    {
      version: '0.5.0',
      date: '2025-11-27',
      content:
        '- 主键命名移除字段名\n- 生成的DDL显示主键命名\n- 导入SQL，解析的主键会沿用系统统一命名规则',
    },
    {
      version: '0.4.1',
      date: '2025-11-21',
      content: '- 导入SQL功能完善\n- 单元测试覆盖率提升',
    },
    {
      version: '0.4.0',
      date: '2025-11-20',
      content:
        '- 新增**分享链接**功能，通过链接分享你的表配置信息\n- 新增**导入SQL**功能，通过SQL语句导入表配置信息\n- 合并**字段配置** **索引配置** **授权配置**\n- 品牌LOGO升级',
    },
    {
      version: '0.3.0',
      date: '2025-11-15',
      content: '- **更新日志**页面样式美化\n- 全新的品牌LOGO\n- 页面样式大升级',
    },
    {
      version: '0.2.4',
      date: '2025-11-12',
      content: '- **Oracle**生成的DDL，增加同义词的创建',
    },
    {
      version: '0.2.3',
      date: '2025-11-09',
      content:
        '- **界面**颜色调整为温暖的颜色\n- **是否为空**列，可以支持「是否YNyn的粘贴」\n- **添加行**只能添加一行问题修复\n- 改善字段名重复或使用数据库保留关键字时的告警提示',
    },
    {
      version: '0.2.2',
      date: '2025-11-03',
      content:
        '- 修复: `mysql`的`timestamp`字段类型，当`默认类型`为`当前时间`时无法配置`更新策略`',
    },
    {
      version: '0.2.1',
      date: '2025-11-03',
      content: '- 修复: **一键清空**按钮部分失效问题',
    },
    {
      version: '0.2.0',
      date: '2025-11-02',
      content: '- 界面样式调整',
    },
    {
      version: '0.1.0',
      date: '2025-10-28',
      content: '- 重构代码',
    },
    {
      version: '0.0.5',
      date: '2025-10-25',
      content:
        '### 新增\n- 表名变更时，自动更新索引名称\n\n### 修复\n- 修正 MySQL 时间戳精度\n- 修正 Oracle 默认约束顺序',
    },
    {
      version: '0.0.4',
      date: '2025-10-24',
      content:
        '### 新增\n- 主键支持，含唯一约束索引配置 (fix #1)\n- 字符类型字段支持 UUID 默认值 (fix #2)\n\n### 重构\n- 清空按钮移至左侧配置面板 (fix #3)',
    },
    {
      version: '0.0.3',
      date: '2025-10-18',
      content:
        '### 新增\n- 索引与权限配置支持折叠\n- 索引配置，支持持久化\n\n### 重构\n- 项目配置现代化\n\n### 测试\n- 核心功能测试覆盖 100%',
    },
    {
      version: '0.0.2',
      date: '2025-10-16',
      content:
        '### 新增\n- 字段默认值与更新策略\n- 字段名校验（重复、关键字高亮）\n- 批量添加行\n- Oracle 支持\n- DDL 复制按钮\n- 本地持久化\n\n### 优化\n- DDL 可读性与交互\n- UI 主题（白底）\n- 表格列精简\n\n### 文档\n- 重写 README\n- 补充项目简介、特性与使用说明\n- 完善类型映射与 DDL 生成要点',
    },
    {
      version: '0.0.1',
      date: '2025-10-15',
      content:
        '### 诞生\n- 筑表师：一个用于设计数据库表结构并生成 DDL 的 Web 工具。\n- 支持 MySQL, PostgreSQL, SQL Server。',
    },
  ],
} as ChangelogData;
