// This file is auto-generated by parseChangelog.ts
// Do not edit this file manually

export interface ChangelogEntry {
  version: string;
  date: string;
  content: string;
  title?: string;
}

export interface ChangelogData {
  title: string;
  description: string;
  entries: ChangelogEntry[];
}

export const changelogData: ChangelogData = {
  title: '筑表师更新日志',
  description: 'DDL建表工具版本更新记录',
  entries: [
    {
      version: '0.13.0',
      date: '2026-02-10',
      content:
        '### 新增\n- **大师建表工坊**：支持通过 AI 快速生成表结构草案，降低建表起步成本\n- **字段重命名识别**：结构调整时可识别字段“改名”场景，减少误判为删除后重建\n- **回滚脚本生成**：支持生成回退用 DDL，变更后可更快恢复到之前状态\n- **导入 SQL 解析校验增强**：新增服务端校验通道，导入与解析结果更可靠\n\n### 优化\n- **表格编辑体验升级**：数据表编辑内核升级，冻结列显示更清晰、操作更顺畅\n- **页面加载速度提升**：导入弹窗、SQL 展示等模块按需加载，打开与切换更快\n- **大师响应更稳定**：增加重试与限流机制，高峰场景下成功率更高\n- **反馈展示更连贯**：长文本输出与评审结果的展示过程更平滑\n- **整体可维护性提升**：应用状态与业务逻辑模块化拆分，后续迭代更稳定\n\n### 稳定性与安全\n- 输入校验与安全策略增强，降低异常输入带来的风险\n- 新增统一异常兜底与上报能力，页面出错时反馈更清晰\n- 无障碍支持完善：键盘操作与读屏体验进一步提升\n- 补充多类自动化与单元测试，核心流程回归保障增强\n\n### 工程与维护\n- 统一依赖管理与测试命令，版本维护与质量检查流程更清晰\n- 持续完善评估与进度文档，便于团队追踪版本演进',
    },
    {
      version: '0.12.0',
      date: '2026-02-06',
      content:
        '### 新增\n- **数据库扩展**：新增 GaussDB、Kingbase、GBase、PolarDB 的 DDL 生成支持，并同步完善类型映射与策略工厂接入\n- **SQL 导入升级**：导入流程升级为「校验 → 预览 → 确认」三步模式，支持导入前字段预览与编辑\n- **表级杂项配置**：新增表级选项面板，可按数据库生成 `ENGINE`、`CHARSET`、`COLLATION`、`TABLESPACE` 等配置\n- **E2E 自动化测试**：引入 Playwright 测试框架，覆盖核心功能、配置面板、工具能力与存储管理流程\n\n### 优化\n- 对话框无障碍与交互体验增强：补充 `aria-label`、焦点样式优化\n- Vercel Analytics 改为懒加载，降低首屏加载开销\n- 调整 E2E 选择器与测试配置，提升自动化用例稳定性\n- 调整 Vitest 配置，排除 E2E 目录，避免与单测执行互相干扰\n- 字段配置表格新增冻结配置：可选择是否开启冻结，并可自定义冻结列数（默认 3 列）\n\n### 测试与维护\n- 增加并完善多模块测试用例，提升回归保障能力\n- 依赖更新：OpenAI、`@types/node`、`@types/react`、Biome 等',
    },
    {
      version: '0.11.0',
      date: '2026-02-02',
      content:
        '### 新增\n- **字段模板管理**：支持字段模板的增删改查、字段排序、保存当前表为模板\n- **文件夹管理**：已保存表支持文件夹分组管理，新增 UI 组件与数据库集成\n- **表版本历史**：支持版本回滚与对比，新增对话框 UI 和 IndexedDB 版本控制\n- **表差异对比**：实现表结构 Diff 与 ALTER DDL 生成，新增变更查看对话框\n- **评审记录历史**：支持查看历史评审记录\n- **评审建议应用**：支持一键应用评审建议到当前表配置\n- **SQL 解释说明**：选中 DDL 语句后可查看 AI 解释说明\n- **存储容量估算器**：支持 MySQL、PostgreSQL、TiDB、OceanBase 等主流数据库的物理磁盘占用预估，包含架构特性说明与交互式容量规划\n\n### 优化\n- 已保存表列表支持字段数徽章、数据库类型图标、实时搜索过滤\n- Tab 页切换动画与 Toast 通知样式改进\n- 评审历史项可访问性与结构优化，Explain 弹窗事件处理提升\n- 部分 JSON 解析增强，可从建议数组中提取完整字符串与对象项\n\n### 测试与维护\n- 新增 hooks 与 utils 的单元测试，覆盖率提升\n- 依赖更新：React、OpenAI、Hono、Biome、Autoprefixer 等',
    },
    {
      version: '0.10.0',
      date: '2026-01-26',
      content:
        '### 新增\n- 已保存表抽屉：通过「查看已保存表」入口打开，支持加载、重命名、删除与当前加载状态标记\n- 保存表持久化到 IndexedDB，名称去重并支持已加载表覆盖更新\n\n### 优化\n- 已加载且未变更的表切换不再提示，变更后才需确认\n- 表配置区域加入保存入口与加载/修改状态提示\n- 已保存表入口弱化为轻量入口，并在入口右侧显示当前加载表名\n- DDL 评审支持流式渲染与部分 JSON 解析，提升反馈速度\n- 评审展示在流式阶段保持骨架提示\n- UI 模块懒加载与渲染性能优化\n\n### 测试与维护\n- 新增 savedTables、DDL Review、partial JSON、IndexedDB 的单测\n- 覆盖率提升至 80% 以上\n- 依赖版本更新（Biome、Vitest 等）',
    },
    {
      version: '0.9.0',
      date: '2026-01-19',
      content:
        '### 新增「大师评审」功能\n- 在 DDL 输出面板新增「大师评审」按钮\n- 基于 AI 大模型对生成的 DDL 进行专业评审\n- 从命名规范、数据类型、索引设计、完整性约束、可扩展性、性能等维度评分\n- 提供 1-10 分的综合评分和改进建议',
    },
    {
      version: '0.8.4',
      date: '2026-01-15',
      content: '- 一些微小的更新',
    },
    {
      version: '0.8.3',
      date: '2025-12-31',
      content: '- 新年快乐',
    },
    {
      version: '0.8.2',
      date: '2025-12-29',
      content: '- 一些微小的更新',
    },
    {
      version: '0.8.1',
      date: '2025-12-28',
      content:
        '### 分区配置增强\n- 支持分区表达式：HASH/KEY/RANGE/LIST 类型可使用函数表达式如 `YEAR(col)`、`dayofmonth(col)`\n- RANGE 分区快捷生成：新增「按年」「按月」「按日」快捷按钮，一键生成常用分区',
    },
    {
      version: '0.8.0',
      date: '2025-12-27',
      content:
        '### 新增MySQL 分区表配置\n- 新增「分区配置」Tab 页，支持 MySQL、MariaDB、TiDB\n- 支持 6 种分区类型：RANGE、RANGE COLUMNS、LIST、LIST COLUMNS、HASH、KEY\n- 每种分区类型配有说明，帮助用户选择合适的分区策略\n- HASH/KEY 分区支持配置分区数量\n- RANGE/LIST 分区支持自定义分区定义\n- DDL 自动生成对应的分区语句',
    },
    {
      version: '0.7.0',
      date: '2025-12-24',
      content:
        '### 新增数据库支持\n- 新增 **MariaDB** 数据库类型支持\n- 新增 **TiDB** 数据库类型支持\n- 新增 **达梦 (Dameng)** 数据库类型支持\n- 新增 **OceanBase** 数据库支持（MySQL 模式 & Oracle 模式）\n- 新增 **PostgreSQL Citus** 数据库类型支持\n\n### Citus 分片配置\n- 新增「分片配置」Tab 页，仅在选择 PostgreSQL Citus 时显示\n- 支持配置表模式：副本表 (Reference Table) 或分片表 (Distributed Table)\n- 分片表模式下可选择分片字段\n- DDL 自动生成 `create_reference_table()` 或 `create_distributed_table()` 语句',
    },
    {
      version: '0.6.5',
      date: '2025-12-19',
      content:
        '- 修复 COMMENT 解析对转义单引号的支持，避免截断注释内容\n- Oracle 索引名按 30 字符限制生成，避免超长\n- 默认值包含 “default” 时按常量处理并正确加引号',
    },
    {
      version: '0.6.4',
      date: '2025-12-18',
      content: '- 一些微小的更新',
    },
    {
      version: '0.6.3',
      date: '2025-12-17',
      content: '- 一些微小的更新',
    },
    {
      version: '0.6.2',
      date: '2025-12-16',
      content: '- 一些微小的更新',
    },
    {
      version: '0.6.1',
      date: '2025-12-15',
      content: '- 一些微小的更新',
    },
    {
      version: '0.6.0',
      date: '2025-12-11',
      content:
        '- 索引名称显示优化：长名称自动换行，不再超出卡片边界\n- 索引名称自动截断：超过40字符时自动截断并添加哈希后缀确保唯一性\n- 新增双击编辑索引名称功能，支持自定义索引名称',
    },
    {
      version: '0.5.0',
      date: '2025-11-27',
      content:
        '- 主键命名移除字段名\n- 生成的DDL显示主键命名\n- 导入SQL，解析的主键会沿用系统统一命名规则',
    },
    {
      version: '0.4.1',
      date: '2025-11-21',
      content: '- 导入SQL功能完善\n- 单元测试覆盖率提升',
    },
    {
      version: '0.4.0',
      date: '2025-11-20',
      content:
        '- 新增**分享链接**功能，通过链接分享你的表配置信息\n- 新增**导入SQL**功能，通过SQL语句导入表配置信息\n- 合并**字段配置** **索引配置** **授权配置**\n- 品牌LOGO升级',
    },
    {
      version: '0.3.0',
      date: '2025-11-15',
      content: '- **更新日志**页面样式美化\n- 全新的品牌LOGO\n- 页面样式大升级',
    },
    {
      version: '0.2.4',
      date: '2025-11-12',
      content: '- **Oracle**生成的DDL，增加同义词的创建',
    },
    {
      version: '0.2.3',
      date: '2025-11-09',
      content:
        '- **界面**颜色调整为温暖的颜色\n- **是否为空**列，可以支持「是否YNyn的粘贴」\n- **添加行**只能添加一行问题修复\n- 改善字段名重复或使用数据库保留关键字时的告警提示',
    },
    {
      version: '0.2.2',
      date: '2025-11-03',
      content:
        '- 修复: `mysql`的`timestamp`字段类型，当`默认类型`为`当前时间`时无法配置`更新策略`',
    },
    {
      version: '0.2.1',
      date: '2025-11-03',
      content: '- 修复: **一键清空**按钮部分失效问题',
    },
    {
      version: '0.2.0',
      date: '2025-11-02',
      content: '- 界面样式调整',
    },
    {
      version: '0.1.0',
      date: '2025-10-28',
      content: '- 重构代码',
    },
    {
      version: '0.0.5',
      date: '2025-10-25',
      content:
        '### 新增\n- 表名变更时，自动更新索引名称\n\n### 修复\n- 修正 MySQL 时间戳精度\n- 修正 Oracle 默认约束顺序',
    },
    {
      version: '0.0.4',
      date: '2025-10-24',
      content:
        '### 新增\n- 主键支持，含唯一约束索引配置 (fix #1)\n- 字符类型字段支持 UUID 默认值 (fix #2)\n\n### 重构\n- 清空按钮移至左侧配置面板 (fix #3)',
    },
    {
      version: '0.0.3',
      date: '2025-10-18',
      content:
        '### 新增\n- 索引与权限配置支持折叠\n- 索引配置，支持持久化\n\n### 重构\n- 项目配置现代化\n\n### 测试\n- 核心功能测试覆盖 100%',
    },
    {
      version: '0.0.2',
      date: '2025-10-16',
      content:
        '### 新增\n- 字段默认值与更新策略\n- 字段名校验（重复、关键字高亮）\n- 批量添加行\n- Oracle 支持\n- DDL 复制按钮\n- 本地持久化\n\n### 优化\n- DDL 可读性与交互\n- UI 主题（白底）\n- 表格列精简\n\n### 文档\n- 重写 README\n- 补充项目简介、特性与使用说明\n- 完善类型映射与 DDL 生成要点',
    },
    {
      version: '0.0.1',
      date: '2025-10-15',
      content:
        '### 诞生\n- 筑表师：一个用于设计数据库表结构并生成 DDL 的 Web 工具。\n- 支持 MySQL, PostgreSQL, SQL Server。',
    },
  ],
} as ChangelogData;
