// This file is auto-generated by parseChangelog.ts
// Do not edit this file manually

export type ChangelogLocale = 'zh-CN' | 'en-US';

export interface ChangelogEntry {
  version: string;
  date: string;
  content: string;
  title?: string;
}

export interface ChangelogData {
  title: string;
  description: string;
  entries: ChangelogEntry[];
}

export const changelogDataMap: Record<ChangelogLocale, ChangelogData> = {
  'zh-CN': {
    title: '筑表师更新日志',
    description: 'DDL建表工具版本更新记录',
    entries: [
      {
        version: '0.14.0',
        date: '2026-02-25',
        content:
          '### 新增\n- **字段与对象拖拽整理**：支持字段顺序拖拽并同步 DDL；已保存表与文件夹支持拖拽整理。\n- **模板编辑升级**：模板字段编辑改为可排序表格，插入模板与切换流程更顺畅。\n- **分享体验增强**：分享流程增加加载态、防重复提交，并支持自动加载分享副本与版本计数。\n- **主题与语言能力扩展**：新增深色主题、跟随系统主题与平滑切换动画；完善英文界面与双语更新日志。\n\n### 优化\n- **工作区持久化升级**：工作区状态迁移至 IndexedDB，并引入启动缓存，刷新与重开后的状态恢复更稳定。\n- **表格编辑体验提升**：改进单元格选中与输入行为，修复点击编辑首字符丢失、输入框粘贴干扰等问题。\n- **结构联动更完整**：字段重命名可同步更新索引、分区与分片配置，减少手工修正。\n- **SQL 导入能力增强**：MySQL 导入补全分区、表级杂项配置与授权对象解析。\n- **界面细节打磨**：搜索型数据库选择器、按钮/抽屉交互样式、提示与骨架反馈进一步优化。\n\n### 稳定性与安全\n- 新增 OpenAI 调用治理能力（频率限制与日预算控制），高峰期可用性更稳。\n- 新增可配置 CSP 安全头与环境开关，部署安全策略更灵活。\n- 增强单元测试与 E2E 覆盖，核心流程回归保障进一步提高。\n\n### 品牌\n- 更新 favicon 与品牌 Logo 资源。',
      },
      {
        version: '0.13.1',
        date: '2026-02-11',
        content: '- 一些微小的更新',
      },
      {
        version: '0.13.0',
        date: '2026-02-10',
        content:
          '### 新增\n- **大师建表工坊**：支持通过 AI 快速生成表结构草案，降低建表起步成本\n- **字段重命名识别**：结构调整时可识别字段“改名”场景，减少误判为删除后重建\n- **回滚脚本生成**：支持生成回退用 DDL，变更后可更快恢复到之前状态\n- **导入 SQL 解析校验增强**：新增服务端校验通道，导入与解析结果更可靠\n\n### 优化\n- **表格编辑体验升级**：数据表编辑内核升级，冻结列显示更清晰、操作更顺畅\n- **页面加载速度提升**：导入弹窗、SQL 展示等模块按需加载，打开与切换更快\n- **大师响应更稳定**：增加重试与限流机制，高峰场景下成功率更高\n- **反馈展示更连贯**：长文本输出与评审结果的展示过程更平滑\n- **整体可维护性提升**：应用状态与业务逻辑模块化拆分，后续迭代更稳定\n\n### 稳定性与安全\n- 输入校验与安全策略增强，降低异常输入带来的风险\n- 新增统一异常兜底与上报能力，页面出错时反馈更清晰\n- 无障碍支持完善：键盘操作与读屏体验进一步提升\n- 补充多类自动化与单元测试，核心流程回归保障增强\n\n### 工程与维护\n- 统一依赖管理与测试命令，版本维护与质量检查流程更清晰\n- 持续完善评估与进度文档，便于团队追踪版本演进',
      },
      {
        version: '0.12.0',
        date: '2026-02-06',
        content:
          '### 新增\n- **数据库扩展**：新增 GaussDB、Kingbase、GBase、PolarDB 的 DDL 生成支持，并同步完善类型映射与策略工厂接入\n- **SQL 导入升级**：导入流程升级为「校验 → 预览 → 确认」三步模式，支持导入前字段预览与编辑\n- **表级杂项配置**：新增表级选项面板，可按数据库生成 `ENGINE`、`CHARSET`、`COLLATION`、`TABLESPACE` 等配置\n- **E2E 自动化测试**：引入 Playwright 测试框架，覆盖核心功能、配置面板、工具能力与存储管理流程\n\n### 优化\n- 对话框无障碍与交互体验增强：补充 `aria-label`、焦点样式优化\n- Vercel Analytics 改为懒加载，降低首屏加载开销\n- 调整 E2E 选择器与测试配置，提升自动化用例稳定性\n- 调整 Vitest 配置，排除 E2E 目录，避免与单测执行互相干扰\n- 字段配置表格新增冻结配置：可选择是否开启冻结，并可自定义冻结列数（默认 3 列）\n\n### 测试与维护\n- 增加并完善多模块测试用例，提升回归保障能力\n- 依赖更新：OpenAI、`@types/node`、`@types/react`、Biome 等',
      },
      {
        version: '0.11.0',
        date: '2026-02-02',
        content:
          '### 新增\n- **字段模板管理**：支持字段模板的增删改查、字段排序、保存当前表为模板\n- **文件夹管理**：已保存表支持文件夹分组管理，新增 UI 组件与数据库集成\n- **表版本历史**：支持版本回滚与对比，新增对话框 UI 和 IndexedDB 版本控制\n- **表差异对比**：实现表结构 Diff 与 ALTER DDL 生成，新增变更查看对话框\n- **评审记录历史**：支持查看历史评审记录\n- **评审建议应用**：支持一键应用评审建议到当前表配置\n- **SQL 解释说明**：选中 DDL 语句后可查看 AI 解释说明\n- **存储容量估算器**：支持 MySQL、PostgreSQL、TiDB、OceanBase 等主流数据库的物理磁盘占用预估，包含架构特性说明与交互式容量规划\n\n### 优化\n- 已保存表列表支持字段数徽章、数据库类型图标、实时搜索过滤\n- Tab 页切换动画与 Toast 通知样式改进\n- 评审历史项可访问性与结构优化，Explain 弹窗事件处理提升\n- 部分 JSON 解析增强，可从建议数组中提取完整字符串与对象项\n\n### 测试与维护\n- 新增 hooks 与 utils 的单元测试，覆盖率提升\n- 依赖更新：React、OpenAI、Hono、Biome、Autoprefixer 等',
      },
      {
        version: '0.10.0',
        date: '2026-01-26',
        content:
          '### 新增\n- 已保存表抽屉：通过「查看已保存表」入口打开，支持加载、重命名、删除与当前加载状态标记\n- 保存表持久化到 IndexedDB，名称去重并支持已加载表覆盖更新\n\n### 优化\n- 已加载且未变更的表切换不再提示，变更后才需确认\n- 表配置区域加入保存入口与加载/修改状态提示\n- 已保存表入口弱化为轻量入口，并在入口右侧显示当前加载表名\n- DDL 评审支持流式渲染与部分 JSON 解析，提升反馈速度\n- 评审展示在流式阶段保持骨架提示\n- UI 模块懒加载与渲染性能优化\n\n### 测试与维护\n- 新增 savedTables、DDL Review、partial JSON、IndexedDB 的单测\n- 覆盖率提升至 80% 以上\n- 依赖版本更新（Biome、Vitest 等）',
      },
      {
        version: '0.9.0',
        date: '2026-01-19',
        content:
          '### 新增「大师评审」功能\n- 在 DDL 输出面板新增「大师评审」按钮\n- 基于 AI 大模型对生成的 DDL 进行专业评审\n- 从命名规范、数据类型、索引设计、完整性约束、可扩展性、性能等维度评分\n- 提供 1-10 分的综合评分和改进建议',
      },
      {
        version: '0.8.4',
        date: '2026-01-15',
        content: '- 一些微小的更新',
      },
      {
        version: '0.8.3',
        date: '2025-12-31',
        content: '- 新年快乐',
      },
      {
        version: '0.8.2',
        date: '2025-12-29',
        content: '- 一些微小的更新',
      },
      {
        version: '0.8.1',
        date: '2025-12-28',
        content:
          '### 分区配置增强\n- 支持分区表达式：HASH/KEY/RANGE/LIST 类型可使用函数表达式如 `YEAR(col)`、`dayofmonth(col)`\n- RANGE 分区快捷生成：新增「按年」「按月」「按日」快捷按钮，一键生成常用分区',
      },
      {
        version: '0.8.0',
        date: '2025-12-27',
        content:
          '### 新增MySQL 分区表配置\n- 新增「分区配置」Tab 页，支持 MySQL、MariaDB、TiDB\n- 支持 6 种分区类型：RANGE、RANGE COLUMNS、LIST、LIST COLUMNS、HASH、KEY\n- 每种分区类型配有说明，帮助用户选择合适的分区策略\n- HASH/KEY 分区支持配置分区数量\n- RANGE/LIST 分区支持自定义分区定义\n- DDL 自动生成对应的分区语句',
      },
      {
        version: '0.7.0',
        date: '2025-12-24',
        content:
          '### 新增数据库支持\n- 新增 **MariaDB** 数据库类型支持\n- 新增 **TiDB** 数据库类型支持\n- 新增 **达梦 (Dameng)** 数据库类型支持\n- 新增 **OceanBase** 数据库支持（MySQL 模式 & Oracle 模式）\n- 新增 **PostgreSQL Citus** 数据库类型支持\n\n### Citus 分片配置\n- 新增「分片配置」Tab 页，仅在选择 PostgreSQL Citus 时显示\n- 支持配置表模式：副本表 (Reference Table) 或分片表 (Distributed Table)\n- 分片表模式下可选择分片字段\n- DDL 自动生成 `create_reference_table()` 或 `create_distributed_table()` 语句',
      },
      {
        version: '0.6.5',
        date: '2025-12-19',
        content:
          '- 修复 COMMENT 解析对转义单引号的支持，避免截断注释内容\n- Oracle 索引名按 30 字符限制生成，避免超长\n- 默认值包含 “default” 时按常量处理并正确加引号',
      },
      {
        version: '0.6.4',
        date: '2025-12-18',
        content: '- 一些微小的更新',
      },
      {
        version: '0.6.3',
        date: '2025-12-17',
        content: '- 一些微小的更新',
      },
      {
        version: '0.6.2',
        date: '2025-12-16',
        content: '- 一些微小的更新',
      },
      {
        version: '0.6.1',
        date: '2025-12-15',
        content: '- 一些微小的更新',
      },
      {
        version: '0.6.0',
        date: '2025-12-11',
        content:
          '- 索引名称显示优化：长名称自动换行，不再超出卡片边界\n- 索引名称自动截断：超过40字符时自动截断并添加哈希后缀确保唯一性\n- 新增双击编辑索引名称功能，支持自定义索引名称',
      },
      {
        version: '0.5.0',
        date: '2025-11-27',
        content:
          '- 主键命名移除字段名\n- 生成的DDL显示主键命名\n- 导入SQL，解析的主键会沿用系统统一命名规则',
      },
      {
        version: '0.4.1',
        date: '2025-11-21',
        content: '- 导入SQL功能完善\n- 单元测试覆盖率提升',
      },
      {
        version: '0.4.0',
        date: '2025-11-20',
        content:
          '- 新增**分享链接**功能，通过链接分享你的表配置信息\n- 新增**导入SQL**功能，通过SQL语句导入表配置信息\n- 合并**字段配置** **索引配置** **授权配置**\n- 品牌LOGO升级',
      },
      {
        version: '0.3.0',
        date: '2025-11-15',
        content:
          '- **更新日志**页面样式美化\n- 全新的品牌LOGO\n- 页面样式大升级',
      },
      {
        version: '0.2.4',
        date: '2025-11-12',
        content: '- **Oracle**生成的DDL，增加同义词的创建',
      },
      {
        version: '0.2.3',
        date: '2025-11-09',
        content:
          '- **界面**颜色调整为温暖的颜色\n- **是否为空**列，可以支持「是否YNyn的粘贴」\n- **添加行**只能添加一行问题修复\n- 改善字段名重复或使用数据库保留关键字时的告警提示',
      },
      {
        version: '0.2.2',
        date: '2025-11-03',
        content:
          '- 修复: `mysql`的`timestamp`字段类型，当`默认类型`为`当前时间`时无法配置`更新策略`',
      },
      {
        version: '0.2.1',
        date: '2025-11-03',
        content: '- 修复: **一键清空**按钮部分失效问题',
      },
      {
        version: '0.2.0',
        date: '2025-11-02',
        content: '- 界面样式调整',
      },
      {
        version: '0.1.0',
        date: '2025-10-28',
        content: '- 重构代码',
      },
      {
        version: '0.0.5',
        date: '2025-10-25',
        content:
          '### 新增\n- 表名变更时，自动更新索引名称\n\n### 修复\n- 修正 MySQL 时间戳精度\n- 修正 Oracle 默认约束顺序',
      },
      {
        version: '0.0.4',
        date: '2025-10-24',
        content:
          '### 新增\n- 主键支持，含唯一约束索引配置 (fix #1)\n- 字符类型字段支持 UUID 默认值 (fix #2)\n\n### 重构\n- 清空按钮移至左侧配置面板 (fix #3)',
      },
      {
        version: '0.0.3',
        date: '2025-10-18',
        content:
          '### 新增\n- 索引与权限配置支持折叠\n- 索引配置，支持持久化\n\n### 重构\n- 项目配置现代化\n\n### 测试\n- 核心功能测试覆盖 100%',
      },
      {
        version: '0.0.2',
        date: '2025-10-16',
        content:
          '### 新增\n- 字段默认值与更新策略\n- 字段名校验（重复、关键字高亮）\n- 批量添加行\n- Oracle 支持\n- DDL 复制按钮\n- 本地持久化\n\n### 优化\n- DDL 可读性与交互\n- UI 主题（白底）\n- 表格列精简\n\n### 文档\n- 重写 README\n- 补充项目简介、特性与使用说明\n- 完善类型映射与 DDL 生成要点',
      },
      {
        version: '0.0.1',
        date: '2025-10-15',
        content:
          '### 诞生\n- 筑表师：一个用于设计数据库表结构并生成 DDL 的 Web 工具。\n- 支持 MySQL, PostgreSQL, SQL Server。',
      },
    ],
  },
  'en-US': {
    title: 'DDLBuilder ChangeLog',
    description: 'DDL Table Creation Tool Version Update Log',
    entries: [
      {
        version: '0.14.0',
        date: '2026-02-25',
        content:
          '### Added\n- **Drag-and-drop organization**: Supports drag-and-drop field reordering with DDL sync, plus drag-and-drop management for saved tables and folders.\n- **Template editing upgrade**: Replaces custom template field editing with a sortable table and smoother apply/switch flow.\n- **Enhanced sharing flow**: Adds loading states, duplicate-request prevention, auto-loading of shared copies, and version count tracking.\n- **Theme and language expansion**: Adds dark theme, system theme following, smooth theme transition, and broader English UI/changelog coverage.\n\n### Improved\n- **Workspace persistence**: Migrates workspace state to IndexedDB and adds bootstrap caching for more reliable recovery after reload/reopen.\n- **Table editing UX**: Improves cell selection/edit behavior and fixes first-character loss and paste interference in input/textarea scenarios.\n- **Stronger schema linkage**: Field rename now propagates to indexes, partitioning, and sharding settings.\n- **Better SQL import**: Enhances MySQL import for partition parsing, table-level misc options, and authorization object handling.\n- **UI polish**: Improves searchable database selector, drawer/button interactions, feedback toasts, and loading skeletons.\n\n### Stability & Security\n- Adds OpenAI governance controls (rate limiting and daily budget) for more stable operation under load.\n- Adds configurable CSP headers with environment-based controls for safer deployments.\n- Expands unit and E2E coverage to strengthen regression safety on core workflows.\n\n### Branding\n- Refreshes favicon and logo assets.',
      },
      {
        version: '0.13.1',
        date: '2026-02-11',
        content: '- Some minor updates',
      },
      {
        version: '0.13.0',
        date: '2026-02-10',
        content:
          '### Added\n- **Master Table Workshop**: Supports generating table structure drafts quickly with AI, reducing the initial cost of table design\n- **Field Rename Detection**: Recognizes field “rename” scenarios during structural adjustments, reducing false positives of delete-and-recreate\n- **Rollback Script Generation**: Supports generating rollback DDL to restore previous states more efficiently after changes\n- **Enhanced SQL Import Parsing Validation**: Added server-side validation channel for more reliable import and parsing results\n\n### Improved\n- **Enhanced Table Editing Experience**: Upgraded data table editing core, clearer frozen column display and smoother operations\n- **Faster Page Loading**: Import modal and SQL display modules now load on demand, improving open and switch performance\n- **More Stable Master Responses**: Added retry and rate-limiting mechanisms to improve success rate during peak usage\n- **Smoother Feedback Presentation**: Improved rendering flow for long text outputs and review results\n- **Improved Maintainability**: Modularized application state and business logic for more stable future iterations\n\n### Stability & Security\n- Enhanced input validation and security policies to reduce risks from abnormal input\n- Added unified exception fallback and reporting mechanism for clearer feedback on page errors\n- Improved accessibility support, including keyboard navigation and screen reader experience\n- Expanded automation and unit tests to strengthen regression coverage of core workflows\n\n### Engineering & Maintenance\n- Unified dependency management and test commands for clearer version maintenance and quality checks\n- Continued improvement of evaluation and progress documentation for better version tracking',
      },
      {
        version: '0.12.0',
        date: '2026-02-06',
        content:
          '### Added\n- **Database Extensions**: Added DDL generation support for GaussDB, Kingbase, GBase, and PolarDB, with completed type mappings and strategy factory integration\n- **SQL Import Upgrade**: Upgraded import workflow to a “Validate → Preview → Confirm” three-step process, supporting field preview and editing before import\n- **Table-Level Misc Configuration**: Added table-level options panel to generate `ENGINE`, `CHARSET`, `COLLATION`, `TABLESPACE`, and other configurations per database\n- **E2E Automated Testing**: Introduced Playwright framework covering core features, configuration panels, tooling capabilities, and storage management flows\n\n### Improved\n- Enhanced dialog accessibility and interaction experience, including `aria-label` additions and focus style optimization\n- Vercel Analytics switched to lazy loading to reduce initial load overhead\n- Adjusted E2E selectors and test configuration to improve automation stability\n- Updated Vitest configuration to exclude E2E directory and avoid conflicts with unit tests\n- Added freeze configuration for field settings table, allowing optional freezing and customizable freeze column count with default of three columns\n\n### Testing & Maintenance\n- Added and improved multi-module test cases to strengthen regression assurance\n- Dependency updates including OpenAI, `@types/node`, `@types/react`, Biome, and others',
      },
      {
        version: '0.11.0',
        date: '2026-02-02',
        content:
          '### Added\n- **Field Template Management**: Supports CRUD operations for field templates, field ordering, and saving current table as template\n- **Folder Management**: Supports folder grouping for saved tables with new UI components and database integration\n- **Table Version History**: Supports version rollback and comparison with new dialog UI and IndexedDB version control\n- **Table Diff Comparison**: Implements table structure diff and ALTER DDL generation with change review dialog\n- **Review History**: Supports viewing historical review records\n- **Apply Review Suggestions**: One-click application of review suggestions to current table configuration\n- **SQL Explanation**: Provides AI-generated explanations for selected DDL statements\n- **Storage Capacity Estimator**: Supports physical disk usage estimation for MySQL, PostgreSQL, TiDB, OceanBase and other major databases, including architecture notes and interactive capacity planning\n\n### Improved\n- Saved table list supports field count badges, database type icons, and real-time search filtering\n- Improved tab switching animations and Toast notification styles\n- Enhanced accessibility and structure of review history items, improved Explain modal event handling\n- Improved JSON parsing logic to extract full string and object items from suggestion arrays\n\n### Testing & Maintenance\n- Added unit tests for hooks and utils, increasing coverage\n- Dependency updates including React, OpenAI, Hono, Biome, Autoprefixer and others',
      },
      {
        version: '0.10.0',
        date: '2026-01-26',
        content:
          '### Added\n- Saved tables drawer accessible via “View Saved Tables”, supporting load, rename, delete, and current load state indicator\n- Persisted saved tables to IndexedDB with deduplicated names and overwrite support for loaded tables\n\n### Improved\n- Switching between loaded and unchanged tables no longer prompts confirmation\n- Added save entry and load or modification state indicator in table configuration area\n- Reduced saved tables entry to lightweight access point with current table name displayed\n- DDL review supports streaming rendering and partial JSON parsing for faster feedback\n- Skeleton indicators shown during streaming review stage\n- UI module lazy loading and rendering performance optimization\n\n### Testing & Maintenance\n- Added unit tests for savedTables, DDL Review, partial JSON, and IndexedDB\n- Coverage increased above 80 percent\n- Updated dependency versions including Biome and Vitest',
      },
      {
        version: '0.9.0',
        date: '2026-01-19',
        content:
          '### Added “Master Review” Feature\n- Added “Master Review” button in DDL output panel\n- Professional AI-based review of generated DDL\n- Evaluation across naming conventions, data types, index design, integrity constraints, scalability, and performance\n- Provides comprehensive score from 1 to 10 with improvement suggestions',
      },
      {
        version: '0.8.4',
        date: '2026-01-15',
        content: '- Some minor updates',
      },
      {
        version: '0.8.3',
        date: '2025-12-31',
        content: '- Happy New Year',
      },
      {
        version: '0.8.2',
        date: '2025-12-29',
        content: '- Some minor updates',
      },
      {
        version: '0.8.1',
        date: '2025-12-28',
        content:
          '### Partition Configuration Enhancement\n- Supports partition expressions for HASH, KEY, RANGE, LIST types such as `YEAR(col)` and `dayofmonth(col)`\n- Quick RANGE partition generation with “By Year”, “By Month”, and “By Day” buttons',
      },
      {
        version: '0.8.0',
        date: '2025-12-27',
        content:
          '### Added MySQL Partition Table Configuration\n- Added “Partition Configuration” tab supporting MySQL, MariaDB, and TiDB\n- Supports six partition types including RANGE, RANGE COLUMNS, LIST, LIST COLUMNS, HASH, and KEY\n- Each partition type includes description to assist selection\n- HASH and KEY partitions support configurable partition count\n- RANGE and LIST partitions support custom partition definitions\n- DDL automatically generates corresponding partition statements',
      },
      {
        version: '0.7.0',
        date: '2025-12-24',
        content:
          '### Added Database Support\n- Added **MariaDB** database type support\n- Added **TiDB** database type support\n- Added **Dameng** database type support\n- Added **OceanBase** database support with MySQL mode and Oracle mode\n- Added **PostgreSQL Citus** database type support\n\n### Citus Sharding Configuration\n- Added “Sharding Configuration” tab shown only when PostgreSQL Citus is selected\n- Supports table modes including Reference Table and Distributed Table\n- Distributed mode allows selection of sharding column\n- DDL automatically generates `create_reference_table()` or `create_distributed_table()` statements',
      },
      {
        version: '0.6.5',
        date: '2025-12-19',
        content:
          '- Fixed COMMENT parsing to support escaped single quotes and prevent truncated comments\n- Oracle index names limited to 30 characters to avoid overflow\n- Default values containing “default” treated as constants and properly quoted',
      },
      {
        version: '0.6.4',
        date: '2025-12-18',
        content: '- Some minor updates',
      },
      {
        version: '0.6.3',
        date: '2025-12-17',
        content: '- Some minor updates',
      },
      {
        version: '0.6.2',
        date: '2025-12-16',
        content: '- Some minor updates',
      },
      {
        version: '0.6.1',
        date: '2025-12-15',
        content: '- Some minor updates',
      },
      {
        version: '0.6.0',
        date: '2025-12-11',
        content:
          '- Optimized index name display with automatic wrapping for long names\n- Automatic index name truncation beyond 40 characters with hash suffix to ensure uniqueness\n- Added double-click editing for index names with custom naming support',
      },
      {
        version: '0.5.0',
        date: '2025-11-27',
        content:
          '- Removed field names from primary key naming\n- Generated DDL now displays primary key naming\n- Imported SQL primary keys follow unified system naming rules',
      },
      {
        version: '0.4.1',
        date: '2025-11-21',
        content:
          '- Improved SQL import functionality\n- Increased unit test coverage',
      },
      {
        version: '0.4.0',
        date: '2025-11-20',
        content:
          '- Added **Share Link** feature to share table configuration via URL\n- Added **Import SQL** feature to import table configuration from SQL\n- Merged **Field Configuration**, **Index Configuration**, and **Privilege Configuration**\n- Brand logo upgrade',
      },
      {
        version: '0.3.0',
        date: '2025-11-15',
        content:
          '- Improved **Changelog** page styling\n- New brand logo\n- Major UI style upgrade',
      },
      {
        version: '0.2.4',
        date: '2025-11-12',
        content: '- Oracle generated DDL now includes synonym creation',
      },
      {
        version: '0.2.3',
        date: '2025-11-09',
        content:
          '- Adjusted interface colors to warmer tones\n- “Nullable” column supports YN and yn paste values\n- Fixed issue where “Add Row” could only add one row\n- Improved warning prompts for duplicate field names or reserved keywords',
      },
      {
        version: '0.2.2',
        date: '2025-11-03',
        content:
          '- Fix: `mysql` `timestamp` field cannot configure update strategy when default type is current time',
      },
      {
        version: '0.2.1',
        date: '2025-11-03',
        content: '- Fix: partial failure of **Clear All** button',
      },
      {
        version: '0.2.0',
        date: '2025-11-02',
        content: '- UI style adjustment',
      },
      {
        version: '0.1.0',
        date: '2025-10-28',
        content: '- Code refactoring',
      },
      {
        version: '0.0.5',
        date: '2025-10-25',
        content:
          '### Added\n- Automatically update index names when table name changes\n\n### Fixed\n- Corrected MySQL timestamp precision\n- Corrected Oracle default constraint order',
      },
      {
        version: '0.0.4',
        date: '2025-10-24',
        content:
          '### Added\n- Primary key support with unique constraint index configuration (fix #1)\n- UUID default value support for character type fields (fix #2)\n\n### Refactored\n- Moved clear button to left configuration panel (fix #3)',
      },
      {
        version: '0.0.3',
        date: '2025-10-18',
        content:
          '### Added\n- Collapsible index and privilege configuration\n- Persistent index configuration\n\n### Refactored\n- Modernized project configuration\n\n### Testing\n- 100 percent coverage for core functionality',
      },
      {
        version: '0.0.2',
        date: '2025-10-16',
        content:
          '### Added\n- Field default values and update strategies\n- Field name validation including duplicates and keyword highlighting\n- Batch row addition\n- Oracle support\n- DDL copy button\n- Local persistence\n\n### Improved\n- DDL readability and interaction\n- UI theme with white background\n- Simplified table columns\n\n### Documentation\n- Rewritten README\n- Added project overview, features, and usage instructions\n- Improved type mapping and DDL generation notes',
      },
      {
        version: '0.0.1',
        date: '2025-10-15',
        content:
          '### Birth\n- Table Craftsman: A web tool for designing database table structures and generating DDL\n- Supports MySQL, PostgreSQL, SQL Server',
      },
    ],
  },
} as Record<ChangelogLocale, ChangelogData>;

export function getChangelogData(locale: ChangelogLocale): ChangelogData {
  return changelogDataMap[locale];
}

export const changelogData: ChangelogData = changelogDataMap['zh-CN'];
